import { TextStyle } from 'react-native';

const wallpaperFontConfig: Record<number, { 
   clock?: string; 
   [key: string]: any;
 }> = { 
  0: { // Dark Solid Color
   
   },
   1: { // Light Solid Color
     
   },
   2: { // Wallpaper/3.jpg
    // home
     time: {'fontFamily': 'RampartOne-Regular', fontSize: 32,color: '#1A2B33'},
     pm: {color: '#1A2B33'},
     date: {color: '#1A2B33'},
     battery: {color: '#3782B8'}, 
     home: {color: '#1A2B33'}, 
     icon: {color: '#1A2B33'}, 
     don: {color: '#405B7F'}, 
     footer: {color: '#1A2B33'}, 
     leave: {color: '#405B7F'}, 
     bottom: { backgroundColor: '#0B303033'}, 
     dialer: { color: '#1A2B33'}, 
     alpha: {color: '#1A2B33'}, 
    //  modal
    modalbg: {backgroundColor: '#FFFFFF'}, 
      open: {color: '#2E3A4C'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#51CDE5'}, 
      number: {color: '#FFFFFF'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#2E3B4D'}, 
      remind: {color: '#2E3B4D'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#A2B9D9'}, 
      quitbg: {backgroundColor: '#42ABBE'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF26'}, 
    searchi: {color: '#5C8BCC'}, 
    allappt: {color: '#1A2B33'},
    allappi: {color: '#1A2B33'}, 
    header: {color: '#192B33'}, 
    applist: {color: '#1A2B33'}, 
    applistbg: {backgroundColor: '#0A26331A'}, 
    appdu: {color: '#1A2B33'}, 
    alphaside: {color: '#1A2B33'}, 
      tikbg: {backgroundColor: '#434C59'},
// category
    searchCbg: {backgroundColor: '#FFFFFF26'}, 
    searchCi: {color: '#5C8BCC'}, 
    searchCt: {color: '#5C8BCC'}, 
    appC: {color: '#1A2B33'},
    appi: {color: '#1A2B33'}, 
    appCn: {color: '#1A2B33'}, 
    appCi: {color: '#1A2B33'}, 
    applistC: {color: '#1A2B33'}, 
    applistCdu: {color: '#1A2B33'}, 
    applistCbg: {backgroundColor: '#0A26331A'}, 
   },
  3: { // Wallpaper/4.jpg
    // home
     time: {'fontFamily': 'RubikMoonrocks-Regular', fontSize: 44,color: '#CEDDF2'},
     pm: {'fontFamily': 'Codystar-Regular', fontSize: 16,color: '#CEDDF2'},
     date: {'fontFamily': 'Poppins-Regular', fontSize: 16,color: '#738099'},
     battery: {color: '#7FA8E5'}, 
     home: {fontFamily: 'Codystar-Regular', fontSize: 20,color: '#CEDDF2'}, 
     icon: { color: '#738099'}, 
     don: {'fontFamily': 'Codystar-Regular',color: '#fff'}, 
     footer: {color: '#CEDDF2'}, 
     leave: {color: '#738099'}, 
     bottom: { backgroundColor: '#73809940'}, 
     dialer: {'fontFamily': 'Codystar-Regular', fontSize: 20, color: '#CEDDF2'}, 
     alpha: {color: '#738099'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#2E3B4D'}, 
      remind: {color: '#2E3B4D'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#A2B9D9'}, 
      quitbg: {backgroundColor: '#42ABBE'}, 
    //  allApps
    searchbg: {backgroundColor: ''}, 
    searchi: {color: '#434C59'}, 
    allappt: {color: '#A3B9D9'}, 
    allappi: {color: '#A3B9D9'}, 
    header: {color: '#728099'}, 
    applist: {fontFamily: 'Codystar-Regular', fontSize: 20,color: '#fff'}, 
    applistbg: {backgroundColor: ''}, 
    appdu: {fontFamily: 'Codystar-Regular', fontSize: 10,color: '#fff'}, 
    alphaside: {color: '#738099'}, 
    tikbg: {backgroundColor: '#434C59'},
// category
    searchCbg: {backgroundColor: ''}, 
    searchCi: {color: '#434C59'},
    searchCt: {color: '#434C59'}, 
    appC: {color: '#A3B9D9'},
    appi: {color: '#A3B9D9'}, 
    appCn: {color: '#405B7F'}, 
    appCi: {color: '#405B7F'}, 
    applistC: {fontFamily: 'Codystar-Regular', fontSize: 20,color: '#fff'}, 
    applistCdu: {fontFamily: 'Codystar-Regular', fontSize: 12,color: '#fff'}, 
    applistCbg: {backgroundColor: ''},
   },
   4: { // Wallpaper/5.jpg
      // home
     time: {'fontFamily': 'Monoton-Regular', fontSize: 44,color: '#FFFFFF',},
     pm: {'fontFamily': 'Poppins-Regular', fontSize: 16,color: '#FFFFFF',},
     date: {'fontFamily': 'Imprima-Regular', fontSize: 16,color: '#FFFFFF',},
     battery: {color: '#FF92B0'}, 
     home: {fontFamily: 'Imprima-Regular', fontSize: 16,color: '#FFFFFF'}, 
     icon: { color: '#FFFFFF'}, 
     don: {'fontFamily': 'Imprima-Regular',color: '#fff'}, 
     footer: {color: '#FFFFFF'}, 
     leave: {'fontFamily': 'Imprima-Regular',color: '#FFFFFF'}, 
     bottom: { backgroundColor: '#73809940'}, 
     dialer: {'fontFamily': 'Imprima-Regular', fontSize: 16, color: '#FFFFFF'}, 
     alpha: {'fontFamily': 'Poppins-Regular',color: '#DADFE5'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#A2B9D9'}, 
      quitbg: {backgroundColor: '#42ABBE'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF40'}, 
    searchi: {color: '#FFFFFF'}, 
    allappt: {color: '#FFFFFF'}, 
    allappi: {color: '#FFFFFF'}, 
    header: {color: '#FFFFFF'}, 
    applist: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#fff'}, 
    applistbg: {backgroundColor: '#0A223333'}, 
    appdu: {fontFamily: 'Imprima-Regular', fontSize: 10,color: '#fff'}, 
    alphaside: {fontFamily: 'Poppins-Regular',color: '#DADFE5'}, 
    tikbg: {backgroundColor: '#FFFFFF40'},
// category
    searchCbg: {backgroundColor: '#FFFFFF40'}, 
    searchCi: {color: '#FFFFFF'},
    searchCt: {color: '#FFFFFF'}, 
      appC: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#FFFFFF'},
      appi: {color: '#FFFFFF'}, 
    appCn: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#FFFFFF'},
    appCi: {color: '#FFFFFF'}, 
    applistC: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#fff'}, 
    applistCdu: {fontFamily: 'Imprima-Regular', fontSize: 12,color: '#fff'}, 
    applistCbg: {backgroundColor: '#0A223333'},
   },
   5: { // Wallpaper/6.jpg
       // home
     time: {'fontFamily': 'Monoton-Regular', fontSize: 44,color: '#FFFFFF',},
     pm: {'fontFamily': 'Poppins-Regular', fontSize: 16,color: '#FFFFFF',},
     date: {'fontFamily': 'Imprima-Regular', fontSize: 16,color: '#FFFFFF',},
     battery: {color: '#FF92B0'}, 
     home: {fontFamily: 'Imprima-Regular', fontSize: 16,color: '#FFFFFF'}, 
     icon: { color: '#FFFFFF'}, 
     don: {'fontFamily': 'Imprima-Regular',color: '#fff'}, 
     footer: {color: '#FFFFFF'}, 
     leave: {'fontFamily': 'Imprima-Regular',color: '#FFFFFF'}, 
     bottom: { backgroundColor: '#73809940'}, 
     dialer: {'fontFamily': 'Imprima-Regular', fontSize: 16, color: '#FFFFFF'}, 
     alpha: {'fontFamily': 'Poppins-Regular',color: '#DADFE5'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#A2B9D9'}, 
      quitbg: {backgroundColor: '#42ABBE'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF40'}, 
    searchi: {color: '#FFFFFF'}, 
    allappt: {color: '#FFFFFF'},
    allappi: {color: '#FFFFFF'}, 
    header: {color: '#FFFFFF'}, 
    applist: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#fff'}, 
    applistbg: {backgroundColor: '#0A223333'}, 
    appdu: {fontFamily: 'Imprima-Regular', fontSize: 10,color: '#fff'}, 
    alphaside: {fontFamily: 'Poppins-Regular',color: '#DADFE5'}, 
    tikbg: {backgroundColor: '#FFFFFF40'},
// category
    searchCbg: {backgroundColor: '#FFFFFF40'}, 
    searchCi: {color: '#FFFFFF'},
    searchCt: {color: '#FFFFFF'}, 
    appC: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#FFFFFF'}, 
    appi: {color: '#FFFFFF'}, 
    appCn: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#FFFFFF'}, 
    appCi: {color: '#FFFFFF'}, 
    applistC: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#fff'}, 
    applistCdu: {fontFamily: 'Imprima-Regular', fontSize: 12,color: '#fff'}, 
    applistCbg: {backgroundColor: '#0A223333'},
   } ,
   6: { // Wallpaper/7.jpg
        // home
    time: {'fontFamily': 'LeagueGothic-Regular', fontSize: 36,color: '#132C4D',},
     pm: {'fontFamily': 'Poppins-Regular', fontSize: 14,color: '#132C4D',},
     date: {'fontFamily': 'Poppins-Regular', fontSize: 14,color: '#132C4D',},
     battery: {color: '#985C99'}, 
     home: {fontFamily: 'Poppins-Regular', fontSize: 16,color: '#132C4D',transform: [{ translateX: -40 }]}, 
     dot: { }, 
     icon: { color: '#132C4D'}, 
     don: {'fontFamily': 'Poppins-Regular',color: '#405B7F'}, 
     footer: {color: '#132C4D'}, 
     leave: {'fontFamily': 'Poppins-Regular',color: '#405B7F'}, 
     bottom: { backgroundColor: '#0B303033'}, 
     dialer: {'fontFamily': 'Poppins-Regular', fontSize: 16, color: '#132C4D'}, 
     alpha: {color: '#405B7F'}, 
    //  modal
    modalbg: {backgroundColor: '#FFFFFF'}, 
      open: {color: '#2E3A4C'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#D982D9'}, 
      number: {color: '#FFFFFF'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#CC70CC'}, 
      when: {color: '#2E3B4D'}, 
      remind: {color: '#2E3B4D'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#CC70CC'}, 
      quitbg: {backgroundColor: '#CC70CC'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF26'}, 
    searchi: {color: '#5C8BCC'}, 
    allappt: {fontFamily: 'Poppins-Regular', fontSize: 20,color: '#132C4D'}, 
    allappi: {color: '#132C4D'}, 
    header: {color: '#132C4D'}, 
    applistbg: {backgroundColor: '#0A26331A'}, 
    applist: {fontFamily: 'Poppins-Regular', fontSize: 18,color: '#132C4D'}, 
    appdu: {fontFamily: 'RobotoMono-Regular', fontSize: 10,color: '#132C4D'}, 
    alphaside: {color: '#405B7F'}, 
    tikbg: {backgroundColor: '#FFFFFF26'},
// category
    searchCbg: {backgroundColor: '#FFFFFF26'}, 
    searchCi: {color: '#5C8BCC'}, 
    searchCt: {color: '#5C8BCC'}, 
    appC: {fontFamily: 'Poppins-Regular', fontSize: 18,color: '#132C4D'}, 
    appi: {color: '#132C4D'}, 
    appCn: {fontFamily: 'Poppins-Regular', fontSize: 18,color: '#132C4D'}, 
    appCi: {color: '#132C4D'}, 
    applistC: {fontFamily: 'Poppins-Regular', fontSize: 18,color: '#132C4D'}, 
    applistCdu: {fontFamily: 'Poppins-Regular', fontSize: 12,color: '#132C4D'}, 
    applistCbg: {backgroundColor: '#0A26331A'},
   },
 7:{ //Wallpaper/8.jpg
     // home
     time: {'fontFamily': 'RubikBurned-Regular', fontSize: 44,color: '#FFFFFF',},
     pm: {'fontFamily': 'Poppins-Regular', fontSize: 16,color: '#FFFFFF',},
     date: {'fontFamily': 'Imprima-Regular', fontSize: 16,color: '#FFFFFF',},
     battery: {color: '#4C6C99'}, 
     home: {fontFamily: 'Imprima-Regular', fontSize: 16,color: '#FFFFFF'}, 
     icon: { color: '#4C6C99'}, 
     don: {'fontFamily': 'Imprima-Regular',color: '#fff'}, 
     footer: {'fontFamily': 'Imprima-Regular',color: '#FFFFFF'}, 
     leave: {'fontFamily': 'Imprima-Regular',color: '#4C6C99'}, 
     bottom: { backgroundColor: '#A2B9D933'}, 
     dialer: {'fontFamily': 'Imprima-Regular', fontSize: 16, color: '#FFFFFF'}, 
     alpha: {'fontFamily': 'Poppins-Regular',color: '#DADFE5'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#434C59'}, 
      quitbg: {backgroundColor: '#212D41'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF1A'}, 
    searchi: {color: '#A2B9D9'}, 
    allappt: {color: '#FFFFFF'}, 
    allappi: {color: '#A2B9D9'}, 
    header: {color: '#FFFFFF'}, 
    applist: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#fff'}, 
    applistbg: {backgroundColor: '#0A223333'}, 
    appdu: {fontFamily: 'Imprima-Regular', fontSize: 10,color: '#fff'}, 
    alphaside: {fontFamily: 'Poppins-Regular',color: '#DADFE5'}, 
    tikbg: {backgroundColor: '#FFFFFF1A'},
// category
    searchCbg: {backgroundColor: '#FFFFFF1A'}, 
    searchCi: {color: '#A2B9D9'}, 
    searchCt: {color: '#A2B9D9'}, 
    appC: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#FFFFFF'}, 
    appi: {color: '#A2B9D9'}, 
    appCn: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#A2B9D9'}, 
    appCi: {color: '#A2B9D9'}, 
    applistC: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#fff'}, 
    applistCdu: {fontFamily: 'Imprima-Regular', fontSize: 12,color: '#fff'}, 
    applistCbg: {backgroundColor: '#0A223333'},
 },
 8:{ //Wallpaper/9.jpg
    // home
     time: {'fontFamily': 'RubikBurned-Regular', fontSize: 44,color: '#992E49',},
     pm: {'fontFamily': 'GreatVibes-Regular', fontSize: 16,color: '#992E49',},
     date: {'fontFamily': 'GreatVibes-Regular', fontSize: 16,color: '#992E49',},
     battery: {color: '#992E49'}, 
     home: {fontFamily: 'GreatVibes-Regular', fontSize: 16,color: '#FF4D79'}, 
     icon: { color: '#992E49'}, 
     don: {'fontFamily': 'GreatVibes-Regular',color: '#993D54'}, 
     footer: {'fontFamily': 'GreatVibes-Regular',color: '#FF668C'}, 
     leave: {'fontFamily': 'GreatVibes-Regular',color: '#992E49'}, 
     bottom: { backgroundColor: '#D9A2A233'}, 
     dialer: {'fontFamily': 'GreatVibes-Regular', fontSize: 16, color: '#FF4C79'}, 
     alpha: {'fontFamily': 'Poppins-Regular',color: '#FF4C79'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#434C59'}, 
      quitbg: {backgroundColor: '#212D41'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF1A'}, 
    searchi: {fontFamily: 'GreatVibes-Regular', fontSize: 16,color: '#FFFFFF4D'}, 
    allappt: {fontFamily: 'GreatVibes-Regular', fontSize: 16,color: '#FFFFFF'}, 
    allappi: {color: '#992E49'}, 
    header: {fontFamily: 'GreatVibes-Regular', fontSize: 16,color: '#FFFFFF'}, 
    applist: {fontFamily: 'GreatVibes-Regular', fontSize: 18,color: '#FF4D79'}, 
    applistbg: {borderColor: '#FFFFFF26', borderWidth: 1}, 
    appdu: {fontFamily: 'GreatVibes-Regular', fontSize: 10,color: '#fff'}, 
    alphaside: {fontFamily: 'Poppins-Regular',color: '#FF4D79'}, 
    tikbg: {backgroundColor: '#FFFFFF1A'},
// category
    searchCbg: {backgroundColor: '#FFFFFF1A'}, 
    searchCi: {color: '#FF668C66'}, 
    searchCt: {fontFamily: 'GreatVibes-Regular', fontSize: 16,color: '#FFFFFF'}, 
    appC: {fontFamily: 'GreatVibes-Regular', fontSize: 18,color: '#FFFFFF'}, 
    appi: {color: '#992E49'}, 
    appCn: {fontFamily: 'GreatVibes-Regular', fontSize: 18,color: '#E6E6E6'}, 
    appCi: {color: '#E6E6E6'}, 
    applistC: {fontFamily: 'GreatVibes-Regular', fontSize: 18,color: '#FF4D79'}, 
    applistCdu: {fontFamily: 'GreatVibes-Regular', fontSize: 12,color: '#FFFFFF'}, 
    applistCbg: {borderColor: '#0A223300', borderWidth: 1}, 
 },
 9:{ //Wallpaper/10.jpg
   // home
     time: {'fontFamily': 'RubikScribble-Regular', fontSize: 44,color: '#FFFFFF',},
     pm: {'fontFamily': 'Imprima-Regular', fontSize: 16,color: '#FFFFFF',},
     date: {'fontFamily': 'Imprima-Regular', fontSize: 16,color: '#FFFFFF',},
     battery: {color: '#FFFFFF'}, 
     home: {fontFamily: 'Imprima-Regular', fontSize: 16,color: '#FFFFFF'}, 
     icon: { color: '#A2B9D9'}, 
     don: {'fontFamily': 'Imprima-Regular',color: '#4C6C99'}, 
     footer: {'fontFamily': 'Imprima-Regular',color: '#FFFFFF'}, 
     leave: {'fontFamily': 'Imprima-Regular',color: '#4C6C99'}, 
     bottom: { backgroundColor: '#A2B9D933'}, 
     dialer: {'fontFamily': 'Imprima-Regular', fontSize: 16, color: '#FFFFFF'}, 
     alpha: {'fontFamily': 'Poppins-Regular',color: '#DADFE5'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#434C59'}, 
      quitbg: {backgroundColor: '#212D41'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF26'}, 
    searchi: {fontFamily: 'Imprima-Regular', fontSize: 16,color: '#A2B9D9'}, 
    allappt: {fontFamily: 'Imprima-Regular', fontSize: 16,color: '#FFFFFF'}, 
    allappi: {color: '#A2B9D9'}, 
    header: {fontFamily: 'Imprima-Regular', fontSize: 16,color: '#FFFFFF'}, 
    applist: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#FFFFFF'}, 
    applistbg: {backgroundColor: '#0A223300'}, 
    appdu: {fontFamily: 'Poppins-Regular', fontSize: 10,color: '#FFFFFF'}, 
    alphaside: {fontFamily: 'Poppins-Regular',color: '#DADFE5'}, 
    tikbg: {backgroundColor: '#FFFFFF26'},
// category
    searchCbg: {backgroundColor: '#FFFFFF26'}, 
    searchCi: {color: '#A2B9D9'}, 
    searchCt: {fontFamily: 'Poppins-Regular', fontSize: 16,color: '#A2B9D9'}, 
    appC: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#FFFFFF'}, 
    appi: {color: '#A2B9D9'}, 
    appCn: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#FFFFFF'}, 
    appCi: {color: '#A2B9D9'}, 
    applistC: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#FFFFFF'}, 
    applistCdu: {fontFamily: 'Imprima-Regular', fontSize: 12,color: '#FFFFFF'}, 
    applistCbg: {backgroundColor: '#0C121B00'}, 
 },
 10:{ //Wallpaper/11.jpg
     // home
     time: {'fontFamily': 'Poppins-Bold', fontSize: 44,color: '#A666FF',},
     pm: {'fontFamily': 'Imprima-Regular', fontSize: 16,color: '#FFFFFF',},
     date: {'fontFamily': 'Imprima-Regular', fontSize: 16,color: '#FFFFFF',},
     battery: {color: '#FFFFFF'}, 
     home: {fontFamily: 'UnicaOne-Regular', fontSize: 16,color: 'red'}, 
     icon: { color: '#A2B9D9'}, 
     don: {'fontFamily': 'Imprima-Regular',color: '#4C6C99'}, 
     footer: {'fontFamily': 'Imprima-Regular',color: '#FFFFFF'}, 
     leave: {'fontFamily': 'Imprima-Regular',color: '#4C6C99'}, 
     bottom: { backgroundColor: '#A2B9D933'}, 
     dialer: {'fontFamily': 'Imprima-Regular', fontSize: 16, color: '#FFFFFF'}, 
     alpha: {'fontFamily': 'Poppins-Regular',color: '#DADFE5'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#434C59'}, 
      quitbg: {backgroundColor: '#212D41'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF26'}, 
    searchi: {fontFamily: 'Imprima-Regular', fontSize: 16,color: '#A2B9D9'}, 
    allappt: {fontFamily: 'Imprima-Regular', fontSize: 16,color: '#FFFFFF'}, 
    allappi: {color: '#A2B9D9'}, 
    header: {fontFamily: 'Imprima-Regular', fontSize: 16,color: '#FFFFFF'}, 
    applist: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#FFFFFF'}, 
    applistbg: {backgroundColor: '#0A223300'}, 
    appdu: {fontFamily: 'Poppins-Regular', fontSize: 10,color: '#FFFFFF'}, 
    alphaside: {fontFamily: 'Poppins-Regular',color: '#DADFE5'}, 
    tikbg: {backgroundColor: '#FFFFFF26'},
// category
    searchCbg: {backgroundColor: '#FFFFFF26'}, 
    searchCi: {color: '#A2B9D9'}, 
    searchCt: {fontFamily: 'Poppins-Regular', fontSize: 16,color: '#A2B9D9'}, 
    appC: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#FFFFFF'}, 
    appi: {color: '#A2B9D9'}, 
    appCn: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#FFFFFF'}, 
    appCi: {color: '#A2B9D9'}, 
    applistC: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#FFFFFF'}, 
    applistCdu: {fontFamily: 'Imprima-Regular', fontSize: 12,color: '#FFFFFF'}, 
    applistCbg: {backgroundColor: '#0C121B00'}, 
 },
 11:{ //Wallpaper/12.jpg
       // home
       time: {'fontFamily': 'Caprasimo-Regular', fontSize: 40,color: '#26E500',},
       pm: {'fontFamily': 'Gugi-Regular', fontSize: 16,color: '#26E500',},
     date: {'fontFamily': 'Gugi-Regular', fontSize: 14,color: '#26E500',},
     battery: {color: '#26E500'}, 
     home: {fontFamily: 'Gugi-Regular', fontSize: 16,color: '#132C4D',}, 
     icon: { color: '#006618'}, 
     don: {'fontFamily': 'Gugi-Regular',color: '#006618'}, 
     footer: {'fontFamily': 'Gugi-Regular',color: '#132C4D'}, 
     leave: {'fontFamily': 'Gugi-Regular',color: '#006618'}, 
     bottom: { backgroundColor: '#A2B9D933'}, 
     dialer: {'fontFamily': 'Gugi-Regular', fontSize: 16, color: '#132C4D'}, 
     alpha: {'fontFamily': 'Poppins-Regular',color: '#DADFE5'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#434C59'}, 
      quitbg: {backgroundColor: '#212D41'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF1A'}, 
    searchi: {fontFamily: 'PlaywriteUSModern-Regular', fontSize: 16,color: '#26E50033'}, 
    allappt: {fontFamily: 'Gugi-Regular', fontSize: 16,color: '#26E500'}, 
    allappi: {color: '#26E500'}, 
    header: {fontFamily: 'Gugi-Regular', fontSize: 16,color: '#26E500'}, 
    applist: {fontFamily: 'Gugi-Regular', fontSize: 18,color: '#26E500'}, 
    applistbg: {backgroundColor: ''}, 
    appdu: {fontFamily: 'Poppins-Regular', fontSize: 10,color: '#26E500'}, 
    alphaside: {fontFamily: 'Poppins-Regular',color: '#FFFFFF'}, 
    tikbg: {backgroundColor: '#FFFFFF1A'},
    wallbg: {backgroundColor: '#0C121BBF'},
// category
    searchCbg: {backgroundColor: '#FFFFFF1A'}, 
    searchCi: {color: '#26E50033'}, 
    searchCt: {fontFamily: 'PlaywriteUSModern-Regular', fontSize: 16,color: '#26E50033'}, 
    appC: {fontFamily: 'Gugi-Regular', fontSize: 18,color: '#26E500'}, 
    appi: {color: '#26E500'}, 
    appCn: {fontFamily: 'Gugi-Regular', fontSize: 14,color: '#26E500'}, 
    appCi: {color: '#26E500'}, 
    applistC: {fontFamily: 'Gugi-Regular', fontSize: 18,color: '#26E500'}, 
    applistCdu: {fontFamily: 'Poppins-Regular', fontSize: 12,color: '#26E500'}, 
    applistCbg: {backgroundColor: ''}, 
 },
 12:{},
 13:{//Wallpaper/14.jpg
     // home
     time: {'fontFamily': 'Gugi-Regular', fontSize: 40,color: '#A37ACC',},
     pm: {'fontFamily': 'Gugi-Regular', fontSize: 16,color: '#A37ACC',},
     date: {'fontFamily': 'Gugi-Regular', fontSize: 13,color: '#A37ACC',},
     battery: {color: '#A37ACC'}, 
     home: {fontFamily: 'Gugi-Regular', fontSize: 16,color: '#FF99D1',}, 
     icon: { color: '#D4CEFE'}, 
     don: {'fontFamily': 'Gugi-Regular',color: '#D4CEFE'}, 
     footer: {'fontFamily': 'Gugi-Regular',color: '#9772BF'}, 
     leave: {'fontFamily': 'Gugi-Regular',color: '#9772BF'}, 
     bottom: { backgroundColor: '#D4CEFC33',borderColor: '#D4CEFC80',borderWidth: 1}, 
     dialer: {'fontFamily': 'Imprima-Regular', fontSize: 16, color: '#A37ACC'}, 
     alpha: {'fontFamily': 'Poppins-Regular',color: '#A37ACC'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#434C59'}, 
      quitbg: {backgroundColor: '#212D41'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF40'}, 
    searchi: {color: '#B781CF40'}, 
    allappt: {fontFamily: 'Gugi-Regular', fontSize: 16,color: '#A37ACC'}, 
    allappi: {color: '#9570BD'}, 
    header: {fontFamily: 'Gugi-Regular', fontSize: 16,color: '#A37ACC'}, 
    applist: {fontFamily: 'Gugi-Regular', fontSize: 18,color: '#A37ACC'}, 
    applistbg: {backgroundColor: '#D4CEFC33'}, 
    appdu: {fontFamily: 'Imprima-Regular', fontSize: 10,color: '#B781CF'}, 
    alphaside: {fontFamily: 'Poppins-Regular',color: '#A37ACC'}, 
    tikbg: {backgroundColor: '#FFFFFF40'},
    wallbg: {backgroundColor: ''},
// category
    searchCbg: {backgroundColor: '#FFFFFF40'}, 
    searchCi: {color: '#B781CF40'}, 
    searchCt: {fontFamily: 'Poppins-Regular', fontSize: 16,color: '#B781CF40'}, 
    appC: {fontFamily: 'Gugi-Regular', fontSize: 18,color: '#A37ACC'}, 
    appi: {color: '#9570BD'}, 
    appCn: {fontFamily: 'Gugi-Regular', fontSize: 14,color: '#A37ACC'}, 
    appCi: {color: '#A37ACC'}, 
    applistC: {fontFamily: 'Gugi-Regular', fontSize: 18,color: '#A37ACC'}, 
    applistCdu: {fontFamily: 'Imprima-Regular', fontSize: 12,color: '#B781CF'}, 
    applistCbg: {backgroundColor: '#D4CEFC33'}, 
 },
 14:{ //Wallpaper/15.jpg
  
  // home
     time: {'fontFamily': 'Shizuru-Regular', fontSize: 44,color: '#FFFFFF',},
     pm: {'fontFamily': 'Gugi-Regular', fontSize: 14,color: '#FFFFFF',},
     date: {'fontFamily': 'Gugi-Regular', fontSize: 14,color: '#FFFFFF',},
     battery: {color: '#FF0000'}, 
     home: {fontFamily: 'MontserratAlternates-Regular', fontSize: 16,color: '#FFFFFF',}, 
     icon: { color: '#FF8080'}, 
     don: {'fontFamily': 'MontserratAlternates-Regular',color: '#FF8080'}, 
     footer: {'fontFamily': 'MontserratAlternates-Regular',color: '#FFFFFF'}, 
     leave: {'fontFamily': 'MontserratAlternates-Regular',color: '#FF8080'}, 
     bottom: { backgroundColor: '#FF000133'}, 
     dialer: {'fontFamily': 'MontserratAlternates-Regular', fontSize: 16, color: '#FFFFFF'}, 
     alpha: {'fontFamily': 'Poppins-Regular',color: '#DADFE5'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#434C59'}, 
      quitbg: {backgroundColor: '#212D41'}, 
    //  allApps
    searchbg: {backgroundColor: '#FF000140'}, 
    searchi: {fontFamily: 'Poppins-Regular', fontSize: 16,color: '#FFFFFF40'}, 
    allappt: {fontFamily: 'Poppins-Regular', fontSize: 16,color: '#FFFFFF'}, 
    allappi: {color: '#FF0000'}, 
    header: {fontFamily: 'Imprima-Regular', fontSize: 16,color: '#FFFFFF'}, 
    applist: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#FFFFFF'}, 
    applistbg: {backgroundColor: '#FF000180'}, 
    appdu: {fontFamily: 'Poppins-Regular', fontSize: 10,color: '#FFFFFF'}, 
    alphaside: {fontFamily: 'Poppins-Regular',color: '#FFFFFF'}, 
    tikbg: {backgroundColor: '#FF000140'},
    wallbg: {backgroundColor: '#0C121B80'},
// category
    searchCbg: {backgroundColor: '#FF000140'}, 
    searchCi: {color: '#FFFFFF40'}, 
    searchCt: {fontFamily: 'Poppins-Regular', fontSize: 16,color: '#FFFFFF40'}, 
    appC: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#FFFFFF'}, 
    appi: {color: '#FF0000'}, 
    appCn: {fontFamily: 'Imprima-Regular', fontSize: 14,color: '#FF0000'}, 
    appCi: {color: '#FF0000'}, 
    applistC: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#FFFFFF'}, 
    applistCdu: {fontFamily: 'Poppins-Regular', fontSize: 12,color: '#FFFFFF'}, 
    applistCbg: {backgroundColor: '#FF000180'}
 },
 15:{ //Wallpaper/16.jpg
    // home
     time: {'fontFamily': 'FredokaOne', fontSize: 44,color: '#FF9500',},
     pm: {'fontFamily': 'MontserratAlternates-Regular', fontSize: 14,color: '#FF9500',},
     date: {'fontFamily': 'MontserratAlternates-Regular', fontSize: 14,color: '#FF9500',},
     battery: {color: '#FF9500'}, 
     home: {fontFamily: 'MontserratAlternates-Regular', fontSize: 16,color: '#FF9500',}, 
     icon: { color: '#808080'}, 
     don: {'fontFamily': 'MontserratAlternates-Regular',color: '#808080'}, 
     footer: {'fontFamily': 'MontserratAlternates-Regular',color: '#FF9500'}, 
     leave: {'fontFamily': 'MontserratAlternates-Regular',color: '#808080'}, 
     bottom: { backgroundColor: '#A2B9D933'}, 
     dialer: {'fontFamily': 'MontserratAlternates-Regular', fontSize: 16, color: '#FFFFFF'}, 
     camera: {'fontFamily': 'MontserratAlternates-Regular', fontSize: 16, color: '#031017'}, 
     alpha: {'fontFamily': 'Poppins-Regular',fontSize: 16,color: '#132C4D'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#FF9500'}, 
      number: {color: '#132C4D'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#FF9500'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#FF9500'}, 
      quitbg: {backgroundColor: '#FF9500'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF1A'}, 
    searchi: {fontFamily: 'Poppins-Regular', fontSize: 16,color: '#A2B9D9'}, 
    allappt: {fontFamily: 'Poppins-Regular', fontSize: 16,color: '#FFFFFF'}, 
    allappi: {color: '#132C4D'}, 
    header: {fontFamily: 'Imprima-Regular', fontSize: 16,color: '#FFFFFF'}, 
    applist: {fontFamily: 'Comfortaa-Regular', fontSize: 18,color: '#FFFFFF'}, 
    applistbg: {backgroundColor: '#FFFFFF1A'}, 
    appdu: {fontFamily: 'Poppins-Regular', fontSize: 10,color: '#132C4D'}, 
    alphaside: {fontFamily: 'Poppins-Regular',color: '#132C4D'}, 
    tikbg: {backgroundColor: '#FFFFFF1A'},
    wallbg: {backgroundColor: ''},
// category
    searchCbg: {backgroundColor: '#FFFFFF1A'}, 
    searchCi: {color: '#A2B9D9'}, 
    searchCt: {fontFamily: 'Poppins-Regular', fontSize: 16,color: '#A2B9D9'}, 
    appC: {fontFamily: 'Poppins-Regular', fontSize: 18,color: '#FFFFFF'}, 
    appi: {color: '#132C4D'}, 
    appCn: {fontFamily: 'Poppins-Regular', fontSize: 14,color: '#132C4D'}, 
    appCi: {color: '#132C4D'}, 
    applistC: {fontFamily: 'Comfortaa-Regular', fontSize: 18,color: '#FFFFFF'}, 
    applistCdu: {fontFamily: 'Poppins-Regular', fontSize: 12,color: '#132C4D'}, 
    applistCbg: {backgroundColor: '#FFFFFF1A'}
 },
 
   
 }; 
 
 
 export default wallpaperFontConfig;