import { TextStyle } from 'react-native';

const wallpaperFontConfig: Record<number, { 
   clock?: string; 
   [key: string]: any;
 }> = { 
  0: { // Dark Solid Color
   
   },
   1: { // Light Solid Color
     
   },
   2: { // Wallpaper/3.jpg
    // home
     time: {'fontFamily': 'RampartOne-Regular', fontSize: 32,color: '#1A2B33'},
     pm: {color: '#1A2B33'},
     date: {color: '#1A2B33'},
     battery: {color: '#3782B8'}, 
     home: {color: '#1A2B33'}, 
     icon: {color: '#1A2B33'}, 
     don: {color: '#405B7F'}, 
     footer: {color: '#1A2B33'}, 
     leave: {color: '#405B7F'}, 
     bottom: { backgroundColor: '#0B303033'}, 
     dialer: { color: '#1A2B33'}, 
     alpha: {color: '#1A2B33'}, 
    //  modal
    modalbg: {backgroundColor: '#FFFFFF'}, 
      open: {color: '#2E3A4C'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#51CDE5'}, 
      number: {color: '#FFFFFF'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#2E3B4D'}, 
      remind: {color: '#2E3B4D'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#A2B9D9'}, 
      quitbg: {backgroundColor: '#42ABBE'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF26'}, 
    searchi: {color: '#5C8BCC'}, 
    allappt: {color: '#1A2B33'}, 
    header: {color: '#192B33'}, 
    applist: {color: '#1A2B33'}, 
    applistbg: {backgroundColor: '#0A26331A'}, 
    appdu: {color: '#1A2B33'}, 
    alphaside: {color: '#1A2B33'}, 
      tikbg: {backgroundColor: '#434C59'},
// category
    searchCbg: {backgroundColor: '#FFFFFF26'}, 
    searchCi: {color: '#5C8BCC'}, 
    appC: {color: '#1A2B33'}, 
    appCn: {color: '#1A2B33'}, 
    appCi: {color: '#1A2B33'}, 
    applistC: {color: '#1A2B33'}, 
    applistCdu: {color: '#1A2B33'}, 
    applistCbg: {backgroundColor: '#0A26331A'}, 
   },
  3: { // Wallpaper/4.jpg
    // home
     time: {'fontFamily': 'RubikMoonrocks-Regular', fontSize: 44,color: '#CEDDF2', transform: [{ translateX: -100 }]},
     pm: {'fontFamily': 'Codystar-Regular', fontSize: 16,color: '#CEDDF2', transform: [{ translateX: -100 }]},
     date: {'fontFamily': 'Poppins-Regular', fontSize: 16,color: '#738099', transform: [{ translateX: -100 }]},
     battery: {color: '#7FA8E5'}, 
     home: {fontFamily: 'Codystar-Regular', fontSize: 20,color: '#CEDDF2'}, 
     icon: { color: '#738099'}, 
     don: {'fontFamily': 'Codystar-Regular',color: '#fff'}, 
     footer: {color: '#CEDDF2'}, 
     leave: {color: '#738099'}, 
     bottom: { backgroundColor: '#73809940'}, 
     dialer: {'fontFamily': 'Codystar-Regular', fontSize: 20, color: '#CEDDF2'}, 
     alpha: {color: '#738099'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#2E3B4D'}, 
      remind: {color: '#2E3B4D'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#A2B9D9'}, 
      quitbg: {backgroundColor: '#42ABBE'}, 
    //  allApps
    searchbg: {backgroundColor: ''}, 
    searchi: {color: '#434C59'}, 
    allappt: {color: '#A3B9D9'}, 
    header: {color: '#728099'}, 
    applist: {fontFamily: 'Codystar-Regular', fontSize: 20,color: '#fff'}, 
    applistbg: {backgroundColor: ''}, 
    appdu: {fontFamily: 'Codystar-Regular', fontSize: 10,color: '#fff'}, 
    alphaside: {color: '#738099'}, 
    tikbg: {backgroundColor: '#434C59'},
// category
    searchCbg: {backgroundColor: ''}, 
    searchCi: {color: '#434C59'}, 
    appC: {color: '#A3B9D9'}, 
    appCn: {color: '#405B7F'}, 
    appCi: {color: '#405B7F'}, 
    applistC: {fontFamily: 'Codystar-Regular', fontSize: 20,color: '#fff'}, 
    applistCdu: {fontFamily: 'Codystar-Regular', fontSize: 12,color: '#fff'}, 
    applistCbg: {backgroundColor: ''},
   },
   4: { // Wallpaper/5.jpg
      // home
     time: {'fontFamily': 'Monoton-Regular', fontSize: 44,color: '#FFFFFF',},
     pm: {'fontFamily': 'Poppins-Regular', fontSize: 16,color: '#FFFFFF',},
     date: {'fontFamily': 'Imprima-Regular', fontSize: 16,color: '#FFFFFF',},
     battery: {color: '#FF92B0'}, 
     home: {fontFamily: 'Imprima-Regular', fontSize: 16,color: '#FFFFFF'}, 
     icon: { color: '#FFFFFF'}, 
     don: {'fontFamily': 'Imprima-Regular',color: '#fff'}, 
     footer: {color: '#FFFFFF'}, 
     leave: {'fontFamily': 'Imprima-Regular',color: '#FFFFFF'}, 
     bottom: { backgroundColor: '#73809940'}, 
     dialer: {'fontFamily': 'Imprima-Regular', fontSize: 16, color: '#FFFFFF'}, 
     alpha: {'fontFamily': 'Poppins-Regular',color: '#DADFE5'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#A2B9D9'}, 
      quitbg: {backgroundColor: '#42ABBE'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF40'}, 
    searchi: {color: '#FFFFFF'}, 
    allappt: {color: '#FFFFFF'}, 
    header: {color: '#FFFFFF'}, 
    applist: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#fff'}, 
    applistbg: {backgroundColor: '#0A223333'}, 
    appdu: {fontFamily: 'Imprima-Regular', fontSize: 10,color: '#fff'}, 
    alphaside: {fontFamily: 'Poppins-Regular',color: '#DADFE5'}, 
    tikbg: {backgroundColor: '#FFFFFF40'},
// category
    searchCbg: {backgroundColor: '#FFFFFF40'}, 
    searchCi: {color: '#FFFFFF'}, 
    appC: {color: '#FFFFFF'}, 
    appCn: {color: '#FFFFFF'}, 
    appCi: {color: '#FFFFFF'}, 
    applistC: {fontFamily: 'Imprima-Regular', fontSize: 18,color: '#fff'}, 
    applistCdu: {fontFamily: 'Imprima-Regular', fontSize: 12,color: '#fff'}, 
    applistCbg: {backgroundColor: '#0A223333'},
   },
   5: { // Wallpaper/6.jpg
      // home
     time: {'fontFamily': 'LeagueGothic-Regular', fontSize: 44,color: '#FFFFFF',},
     pm: {'fontFamily': 'Poppins-Regular', fontSize: 16,color: '#FFFFFF',},
     date: {'fontFamily': 'Imprima-Regular', fontSize: 16,color: '#FFFFFF',},
     battery: {color: '#FF92B0'}, 
     home: {fontFamily: 'Imprima-Regular', fontSize: 16,color: '#FFFFFF'}, 
     icon: { color: '#FFFFFF'}, 
     don: {'fontFamily': 'Imprima-Regular',color: '#fff'}, 
     footer: {color: '#FFFFFF'}, 
     leave: {'fontFamily': 'Imprima-Regular',color: '#FFFFFF'}, 
     bottom: { backgroundColor: '#73809940'}, 
     dialer: {'fontFamily': 'Imprima-Regular', fontSize: 16, color: '#FFFFFF'}, 
     alpha: {color: '#738099'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#2E3B4D'}, 
      remind: {color: '#2E3B4D'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#A2B9D9'}, 
      quitbg: {backgroundColor: '#42ABBE'}, 
    //  allApps
    searchbg: {backgroundColor: ''}, 
    searchi: {color: '#434C59'}, 
    allappt: {color: '#A3B9D9'}, 
    header: {color: '#728099'}, 
    applist: {fontFamily: 'Codystar-Regular', fontSize: 20,color: '#fff'}, 
    applistbg: {backgroundColor: ''}, 
    appdu: {fontFamily: 'Codystar-Regular', fontSize: 10,color: '#fff'}, 
    alphaside: {color: '#738099'}, 
    tikbg: {backgroundColor: '#434C59'},
// category
    searchCbg: {backgroundColor: ''}, 
    searchCi: {color: '#434C59'}, 
    appC: {color: '#A3B9D9'}, 
    appCn: {color: '#405B7F'}, 
    appCi: {color: '#405B7F'}, 
    applistC: {fontFamily: 'Imprima-Regular', fontSize: 20,color: '#fff'}, 
    applistCdu: {fontFamily: 'Imprima-Regular', fontSize: 12,color: '#fff'}, 
    applistCbg: {backgroundColor: ''},
   } ,
   6: { // Wallpaper/7.jpg
        // home
    time: {'fontFamily': 'RubikMoonrocks-Regular', fontSize: 44,color: '#132C4D',},
     pm: {'fontFamily': 'Poppins-Regular', fontSize: 16,color: '#FFFFFF',},
     date: {'fontFamily': 'Imprima-Regular', fontSize: 16,color: '#FFFFFF',},
     battery: {color: '#FF92B0'}, 
     home: {fontFamily: 'Imprima-Regular', fontSize: 16,color: '#FFFFFF'}, 
     icon: { color: '#FFFFFF'}, 
     don: {'fontFamily': 'Imprima-Regular',color: '#fff'}, 
     footer: {color: '#FFFFFF'}, 
     leave: {'fontFamily': 'Imprima-Regular',color: '#FFFFFF'}, 
     bottom: { backgroundColor: '#73809940'}, 
     dialer: {'fontFamily': 'Imprima-Regular', fontSize: 16, color: '#FFFFFF'}, 
     alpha: {color: '#738099'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#2E3B4D'}, 
      remind: {color: '#2E3B4D'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#A2B9D9'}, 
      quitbg: {backgroundColor: '#42ABBE'}, 
    //  allApps
    searchbg: {backgroundColor: ''}, 
    searchi: {color: '#434C59'}, 
    allappt: {color: '#A3B9D9'}, 
    header: {color: '#728099'}, 
    applist: {fontFamily: 'Codystar-Regular', fontSize: 20,color: '#fff'}, 
    applistbg: {backgroundColor: ''}, 
    appdu: {fontFamily: 'Codystar-Regular', fontSize: 10,color: '#fff'}, 
    alphaside: {color: '#738099'}, 
    tikbg: {backgroundColor: '#434C59'},
// category
    searchCbg: {backgroundColor: ''}, 
    searchCi: {color: '#434C59'}, 
    appC: {color: '#A3B9D9'}, 
    appCn: {color: '#405B7F'}, 
    appCi: {color: '#405B7F'}, 
    applistC: {fontFamily: 'Imprima-Regular', fontSize: 20,color: '#fff'}, 
    applistCdu: {fontFamily: 'Imprima-Regular', fontSize: 12,color: '#fff'}, 
    applistCbg: {backgroundColor: ''},
   }

   
 }; 
 
 
 export default wallpaperFontConfig;