import { TextStyle } from 'react-native';

const wallpaperFontConfig: Record<number, { 
   clock?: string; 
   [key: string]: any;
 }> = { 
  0: { // Dark Solid Color
   
   },
   1: { // Light Solid Color
     
   },
   2: { // Wallpaper/3.jpg
    // home
     time: {'fontFamily': 'RampartOne_400Regular', fontSize: 44,color: '#1A2B33'},
     pm: {color: '#1A2B33'},
     date: {color: '#1A2B33'},
     battery: {color: '#3782B8'}, 
     home: {color: '#1A2B33'}, 
     icon: {color: '#1A2B33'}, 
     don: {color: '#405B7F'}, 
     footer: {color: '#1A2B33'}, 
     leave: {color: '#405B7F'}, 
     bottom: { backgroundColor: '#0B303033'}, 
     dialer: { color: '#1A2B33'}, 
     alpha: {color: '#1A2B33'}, 
    //  modal
    modalbg: {backgroundColor: '#FFFFFF'}, 
      open: {color: '#2E3A4C'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#51CDE5'}, 
      number: {color: '#FFFFFF'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#51CDE5'}, 
      when: {color: '#2E3B4D'}, 
      remind: {color: '#2E3B4D'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#A2B9D9'}, 
      quitbg: {backgroundColor: '#42ABBE'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF26'}, 
    searchi: {color: '#5C8BCC'}, 
    allappt: {color: '#1A2B33'},
    allappi: {color: '#1A2B33'}, 
    header: {color: '#192B33'}, 
    applist: {color: '#1A2B33'}, 
    applistbg: {backgroundColor: '#0A26331A'}, 
    appdu: {color: '#1A2B33'}, 
    alphaside: {color: '#1A2B33'}, 
    tikbg: {backgroundColor: '#434C59'},
    bubblebg: {backgroundColor: '#B8E9F9',color: '#192B33', shadowColor: '#0000001A'},
// category
    searchCbg: {backgroundColor: '#FFFFFF26'}, 
    searchCi: {color: '#5C8BCC'}, 
    searchCt: {color: '#5C8BCC'}, 
    appC: {color: '#1A2B33'},
    appi: {color: '#1A2B33'}, 
    appCn: {color: '#1A2B33'}, 
    appCi: {color: '#1A2B33'}, 
    applistC: {color: '#1A2B33'}, 
    applistCdu: {color: '#1A2B33'}, 
    applistCbg: {backgroundColor: '#0A26331A'}, 
    // block1
    block: {backgroundColor: '#ECF0FF'},
    blockText1: {color: '#2E3B4D'},
    blockText2: {color: '#858E9D'},
    blockText3: {color: '#8698B2'},
    blockText4: {color: '#2E3B4D'},
    blockText5: {color: '#2E3B4D'},
    blockbg: {backgroundColor: '#FFFFFF'},
    blockgradient: ['#ECF0FF', '#51CDE4'],
    blockcircle: {backgroundColor: '#43ABBE'},
    blockbutton1: {backgroundColor: '#51CDE5'},
    blockbutton2: {backgroundColor: '#42ABBE'},
    blockbuttontext: {color: '#FFFFFF'},
    // block2
    blockText6: {color: '#2E3B4D'},
    blockText7: {color: '#2E3B4D'},
    blockText8: {color: '#858E9D'},
  //  weekly
    weeklytext1: {color: '#2F3A4D'},
    weeklytext2: {color: '#89A2CA'},
    weekly2: {backgroundColor: '#51CDE5'},
   },
  3: { // Wallpaper/4.jpg
    // home
     time: {'fontFamily': 'RubikMoonrocks_400Regular', fontSize: 56,color: '#CEDDF2'},
     pm: {'fontFamily': 'Codystar_400Regular', fontSize: 16,color: '#CEDDF2'},
     date: {'fontFamily': 'Poppins_400Regular', fontSize: 16,color: '#738099'},
     battery: {color: '#7FA8E5'}, 
     home: {fontFamily: 'Codystar_400Regular', fontSize: 20,color: '#CEDDF2'}, 
     icon: { color: '#738099'}, 
     don: {'fontFamily': 'Codystar_400Regular',color: '#fff'}, 
     footer: {color: '#738099'}, 
     leave: {color: '#738099'}, 
     bottom: { backgroundColor: '#73809920'}, 
     dialer: {'fontFamily': 'Codystar_400Regular', fontSize: 20, color: '#CEDDF2'}, 
     alpha: {color: '#738099'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#2E3B4D'}, 
      remind: {color: '#2E3B4D'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#A2B9D9'}, 
      quitbg: {backgroundColor: '#212D41'}, 
    //  allApps
    searchbg: {backgroundColor: ''}, 
    searchi: {color: '#434C59'}, 
    allappt: {color: '#738099'}, 
    allappi: {color: '#738099'}, 
    header: {color: '#738099'}, 
    applist: {fontFamily: 'Codystar_400Regular', fontSize: 20,color: '#fff'}, 
    applistbg: {backgroundColor: ''}, 
    appdu: {fontFamily: 'Codystar_400Regular', fontSize: 10,color: '#fff'}, 
    alphaside: {color: '#738099'}, 
    tikbg: {backgroundColor: '#434C59'},
    bubblebg: {backgroundColor: '#697F9E',color: '#C3D2E5', shadowColor: '#0000001A'},
// category
    searchCbg: {backgroundColor: ''}, 
    searchCi: {color: '#434C59'},
    searchCt: {color: '#434C59'}, 
    appC: {color: '#738099'},
    appi: {color: '#738099'}, 
    appCn: {color: '#738099'}, 
    appCi: {color: '#738099'}, 
    applistC: {fontFamily: 'Codystar_400Regular', fontSize: 20,color: '#fff'}, 
    applistCdu: {fontFamily: 'Codystar_400Regular', fontSize: 12,color: '#fff'}, 
    applistCbg: {backgroundColor: ''},
    // block1
    block: {backgroundColor: '#131B27'},
    blockText1: {color: '#DBDFE5'},
    blockText2: {color: '#728099'},
    blockText3: {color: '#7FA8E5'},
    blockText4: {color: '#DBDFE5'},
    blockText5: {color: '#DBDFE5'},
    blockbg: {backgroundColor: '#ECF0FF'},
    blockgradient: ['#ECF0FF', '#7EA9E5'],
    blockcircle: {backgroundColor: '#5D8BCC'},
    blockbutton1: {backgroundColor: '#212C40'},
    blockbutton2: {backgroundColor: '#212C40'},
    blockbuttontext: {color: '#FFFFFF'},
    // block2
    blockText6: {color: '#DBDFE5'},
    blockText7: {color: '#DBDFE5'},
    blockText8: {color: '#728099'},
  //  weekly
    weeklytext1: {color: '#DBDFE5'},
    weeklytext2: {color: '#728099'},
    weekly2: {backgroundColor: '#212C40'},
   },
   4: { // Wallpaper/5.jpg
      // home
     time: {'fontFamily': 'Monoton_400Regular', fontSize: 44,color: '#FFFFFF',},
     pm: {'fontFamily': 'Poppins_400Regular', fontSize: 16,color: '#FFFFFF',},
     date: {'fontFamily': 'Imprima_400Regular', fontSize: 16,color: '#FFFFFF',},
     battery: {color: '#FFFFFF'}, 
     home: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#FFFFFF'}, 
     icon: { color: '#738099'}, 
     don: {'fontFamily': 'Imprima_400Regular',color: '#738099'}, 
     footer: {color: '#738099'}, 
     leave: {'fontFamily': 'Imprima_400Regular',color: '#738099'}, 
     bottom: { backgroundColor: '#73809940'}, 
     dialer: {'fontFamily': 'Imprima_400Regular', fontSize: 16, color: '#FFFFFF'}, 
     alpha: {'fontFamily': 'Poppins_400Regular',color: '#DADFE5'}, 
    //  modal
      modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#A2B9D9'}, 
      quitbg: {backgroundColor: '#212D41'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF20'}, 
    searchi: {color: '#FFFFFF40'}, 
    allappt: {color: '#FFFFFF'}, 
    allappi: {color: '#FFFFFF'}, 
    header: {color: '#FFFFFF'}, 
    applist: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#fff'}, 
    applistbg: {backgroundColor: '#0A223333'}, 
    appdu: {fontFamily: 'Imprima_400Regular', fontSize: 10,color: '#fff'}, 
    alphaside: {fontFamily: 'Poppins_400Regular',color: '#DADFE5'}, 
    tikbg: {backgroundColor: '#FFFFFF40'},
    bubblebg: {backgroundColor: '#008EB2',color: '#FFFFFF', shadowColor: '#0000004D'},
// category
    searchCbg: {backgroundColor: '#FFFFFF20'}, 
    searchCi: {color: '#FFFFFF40'},
    searchCt: {color: '#FFFFFF40'}, 
    appC: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#FFFFFF'},
    appi: {color: '#FFFFFF'}, 
    appCn: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#FFFFFF'},
    appCi: {color: '#FFFFFF'}, 
    applistC: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#fff'}, 
    applistCdu: {fontFamily: 'Imprima_400Regular', fontSize: 12,color: '#fff'}, 
    applistCbg: {backgroundColor: '#0A223333'},
    // block1
    block: {backgroundColor: '#131B27'},
    blockText1: {color: '#DBDFE5'},
    blockText2: {color: '#728099'},
    blockText3: {color: '#7FA8E5'},
    blockText4: {color: '#DBDFE5'},
    blockText5: {color: '#DBDFE5'},
    blockbg: {backgroundColor: '#ECF0FF'},
    blockgradient: ['#ECF0FF', '#7EA9E5'],
    blockcircle: {backgroundColor: '#5D8BCC'},
    blockbutton1: {backgroundColor: '#212C40'},
    blockbutton2: {backgroundColor: '#212C40'},
    blockbuttontext: {color: '#FFFFFF'},
    // block2
    blockText6: {color: '#DBDFE5'},
    blockText7: {color: '#DBDFE5'},
    blockText8: {color: '#728099'},
  //  weekly
    weeklytext1: {color: '#DBDFE5'},
    weeklytext2: {color: '#728099'},
    weekly2: {backgroundColor: '#212C40'},
   },
   5: { // Wallpaper/6.jpg
       // home
     time: {'fontFamily': 'RammettoOne_400Regular', fontSize: 44,color: '#FF92B1',},
     pm: {'fontFamily': 'Poppins_400Regular', fontSize: 16,color: '#FF92B1',},
     date: {'fontFamily': 'Imprima_400Regular', fontSize: 16,color: '#FF92B1',},
     battery: {color: '#738099'}, 
     home: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#FFFFFF'}, 
     icon: { color: '#FFFFFF'}, 
     don: {'fontFamily': 'Imprima_400Regular',color: '#738099'}, 
     footer: {color: '#FFF'}, 
     leave: {'fontFamily': 'Imprima_400Regular',color: '#738099'}, 
     bottom: { backgroundColor: '#73809920'}, 
     dialer: {'fontFamily': 'Imprima_400Regular', fontSize: 16, color: '#FFFFFF'}, 
     alpha: {'fontFamily': 'Poppins_400Regular',color: '#DADFE5'}, 
    //  modal
     modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#A2B9D9'}, 
      quitbg: {backgroundColor: '#212D41'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF10'}, 
    searchi: {color: '#FFFFFF40'}, 
    allappt: {color: '#FFFFFF'},
    allappi: {color: '#738099'}, 
    header: {color: '#FFFFFF'}, 
    applist: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#fff'}, 
    applistbg: {backgroundColor: '#0A223333'}, 
    appdu: {fontFamily: 'Imprima_400Regular', fontSize: 10,color: '#738099'}, 
    alphaside: {fontFamily: 'Poppins_400Regular',color: '#DADFE5'}, 
    tikbg: {backgroundColor: '#FFFFFF40'},
    bubblebg: {backgroundColor: '#D9908D',color: '#FFFFFF', shadowColor: '#0000004D'},
// category
    searchCbg: {backgroundColor: '#FFFFFF10'}, 
    searchCi: {color: '#FFFFFF40'},
    searchCt: {color: '#FFFFFF40'}, 
    appC: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#FFFFFF'}, 
    appi: {color: '#738099'}, 
    appCn: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#DADFE5'}, 
    appCi: {color: '#738099'}, 
    applistC: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#fff'}, 
    applistCdu: {fontFamily: 'Imprima_400Regular', fontSize: 10,color: '#738099'}, 
    applistCbg: {backgroundColor: '#0A223333'},
    // block1
    block: {backgroundColor: '#131B27'},
    blockText1: {color: '#DBDFE5'},
    blockText2: {color: '#728099'},
    blockText3: {color: '#7FA8E5'},
    blockText4: {color: '#DBDFE5'},
    blockText5: {color: '#DBDFE5'},
    blockbg: {backgroundColor: '#ECF0FF'},
    blockgradient: ['#ECF0FF', '#7EA9E5'],
    blockcircle: {backgroundColor: '#5D8BCC'},
    blockbutton1: {backgroundColor: '#212C40'},
    blockbutton2: {backgroundColor: '#212C40'},
    blockbuttontext: {color: '#FFFFFF'},
    // block2
    blockText6: {color: '#DBDFE5'},
    blockText7: {color: '#DBDFE5'},
    blockText8: {color: '#728099'},
  //  weekly
    weeklytext1: {color: '#DBDFE5'},
    weeklytext2: {color: '#728099'},
    weekly2: {backgroundColor: '#212C40'},
   } ,
   6: { // Wallpaper/7.jpg
        // home
    time: {'fontFamily': 'LeagueGothic_400Regular', fontSize: 36,color: '#132C4D',},
     pm: {'fontFamily': 'Poppins_400Regular', fontSize: 14,color: '#132C4D',},
     date: {'fontFamily': 'Poppins_400Regular', fontSize: 14,color: '#132C4D',},
     battery: {color: '#985C99'}, 
     home: {fontFamily: 'Poppins_400Regular', fontSize: 18,color: '#132C4D',transform: [{ translateX: -40 }]}, 
     dot: { }, 
     icon: { color: '#132C4D'}, 
     don: {'fontFamily': 'Poppins_400Regular',color: '#405B7F'}, 
     footer: {color: '#132C4D'}, 
     leave: {'fontFamily': 'Poppins_400Regular',color: '#405B7F'}, 
     bottom: { backgroundColor: '#0B303033'}, 
     dialer: {'fontFamily': 'Poppins_400Regular', fontSize: 16, color: '#132C4D'}, 
     alpha: {color: '#405B7F'}, 
    //  modal
    modalbg: {backgroundColor: '#FFFFFF'}, 
      open: {color: '#2E3A4C'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#D982D9'}, 
      number: {color: '#FFFFFF'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#CC70CC'}, 
      when: {color: '#2E3B4D'}, 
      remind: {color: '#2E3B4D'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#CC70CC'}, 
      quitbg: {backgroundColor: '#CC70CC'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF26'}, 
    searchi: {color: '#985C9940'}, 
    allappt: {fontFamily: 'Poppins_400Regular', fontSize: 20,color: '#132C4D'}, 
    allappi: {color: '#985C99'}, 
    header: {color: '#132C4D'}, 
    applistbg: {backgroundColor: '#0A26331A'}, 
    applist: {fontFamily: 'Poppins_400Regular', fontSize: 18,color: '#132C4D'}, 
    appdu: {fontFamily: 'RobotoMono_400Regular', fontSize: 10,color: '#132C4D'}, 
    alphaside: {color: '#405B7F'}, 
    tikbg: {backgroundColor: '#FFFFFF26'},
    bubblebg: {backgroundColor: '#CBCEFF',color: '#132C4D', shadowColor: '#0000001A'},
// category
    searchCbg: {backgroundColor: '#FFFFFF26'}, 
    searchCi: {color: '#985C9940'}, 
    searchCt: {color: '#985C9940'}, 
    appC: {fontFamily: 'Poppins_400Regular', fontSize: 18,color: '#132C4D'}, 
    appi: {color: '#985C99'}, 
    appCn: {fontFamily: 'Poppins_400Regular', fontSize: 18,color: '#132C4D'}, 
    appCi: {color: '#985C99'}, 
    applistC: {fontFamily: 'Poppins_400Regular', fontSize: 18,color: '#132C4D'}, 
    applistCdu: {fontFamily: 'Poppins_400Regular', fontSize: 10,color: '#132C4D'}, 
    applistCbg: {backgroundColor: '#0A26331A'},
    // block1
    block: {backgroundColor: '#FFFFFF'},
    blockText1: {color: '#2E3B4D'},
    blockText2: {color: '#858E9D'},
    blockText3: {color: '#8698B2'},
    blockText4: {color: '#2E3B4D'},
    blockText5: {color: '#2E3B4D'},
    blockbg: {backgroundColor: '#ECF0FF'},
    blockgradient: ['#ECF0FF', '#CC70CC'],
    blockcircle: {backgroundColor: '#995C99'},
    blockbutton1: {backgroundColor: '#CC70CC'},
    blockbutton2: {backgroundColor: '#995C99'},
    blockbuttontext: {color: '#FFFFFF'},
    // block2
    blockText6: {color: '#2E3B4D'},
    blockText7: {color: '#2E3B4D'},
    blockText8: {color: '#858E9D'},
  //  weekly
    weeklytext1: {color: '#2F3A4D'},
    weeklytext2: {color: '#89A2CA'},
    weekly2: {backgroundColor: '#CC70CC'},
   },
 7:{ //Wallpaper/8.jpg
     // home
     time: {'fontFamily': 'RubikBurned_400Regular', fontSize: 44,color: '#FFFFFF',},
     pm: {'fontFamily': 'Poppins_400Regular', fontSize: 16,color: '#FFFFFF',},
     date: {'fontFamily': 'Imprima_400Regular', fontSize: 16,color: '#FFFFFF',},
     battery: {color: '#a2d9cd'}, 
     home: {fontFamily: 'Imprima_400Regular', fontSize: 16,color: '#FFFFFF'}, 
     icon: { color: '#a2d9cd'}, 
     don: {'fontFamily': 'Imprima_400Regular',color: '#6ba397'}, 
     footer: {'fontFamily': 'Imprima_400Regular',color: '#FFFFFF'}, 
     leave: {'fontFamily': 'Imprima_400Regular',color: '#6ba397'}, 
     bottom: { backgroundColor: '#A2B9D933'}, 
     dialer: {'fontFamily': 'Imprima_400Regular', fontSize: 16, color: '#FFFFFF'}, 
     alpha: {'fontFamily': 'Poppins_400Regular',color: '#DADFE5'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#434C59'}, 
      quitbg: {backgroundColor: '#212D41'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF1A'}, 
    searchi: {color: '#a2d9cd40'}, 
    allappt: {color: '#FFFFFF'}, 
    allappi: {color: '#a2d9cd'}, 
    header: {color: '#FFFFFF'}, 
    applist: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#fff'}, 
    applistbg: {backgroundColor: '#0A223333'}, 
    appdu: {fontFamily: 'Imprima_400Regular', fontSize: 10,color: '#6ba397'}, 
    alphaside: {fontFamily: 'Poppins_400Regular',color: '#DADFE5'}, 
    tikbg: {backgroundColor: '#FFFFFF1A'},
    bubblebg: {backgroundColor: '#8DBBBB',color: '#192B33', shadowColor: '#0000001A'},
// category
    searchCbg: {backgroundColor: '#FFFFFF1A'}, 
    searchCi: {color: '#A2B9D940'}, 
    searchCt: {color: '#A2B9D940'}, 
    appC: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#FFFFFF'}, 
    appi: {color: '#a2d9cd'}, 
    appCn: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#a2d9cd'}, 
    appCi: {color: '#a2d9cd'}, 
    applistC: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#fff'}, 
    applistCdu: {fontFamily: 'Imprima_400Regular', fontSize: 10,color: '#6ba397'}, 
    applistCbg: {backgroundColor: '#0A223333'},
    // block1
    block: {backgroundColor: '#131B27'},
    blockText1: {color: '#DBDFE5'},
    blockText2: {color: '#728099'},
    blockText3: {color: '#7FA8E5'},
    blockText4: {color: '#DBDFE5'},
    blockText5: {color: '#DBDFE5'},
    blockbg: {backgroundColor: '#ECF0FF'},
    blockgradient: ['#ECF0FF', '#7EA9E5'],
    blockcircle: {backgroundColor: '#5D8BCC'},
    blockbutton1: {backgroundColor: '#212C40'},
    blockbutton2: {backgroundColor: '#212C40'},
    blockbuttontext: {color: '#FFFFFF'},
    // block2
    blockText6: {color: '#DBDFE5'},
    blockText7: {color: '#DBDFE5'},
    blockText8: {color: '#728099'},
  //  weekly
    weeklytext1: {color: '#DBDFE5'},
    weeklytext2: {color: '#728099'},
    weekly2: {backgroundColor: '#212C40'},
 },
 8:{ //Wallpaper/9.jpg
    // home
     time: {'fontFamily': 'RubikBurned_400Regular', fontSize: 44,color: '#992E49',},
     pm: {'fontFamily': 'GreatVibes_400Regular', fontSize: 16,color: '#992E49',},
     date: {'fontFamily': 'GreatVibes_400Regular', fontSize: 16,color: '#992E49',},
     battery: {color: '#992E49'}, 
     home: {fontFamily: 'GreatVibes_400Regular', fontSize: 16,color: '#FF4D79'}, 
     icon: { color: '#992E49'}, 
     don: {'fontFamily': 'GreatVibes_400Regular',color: '#993D54'}, 
     footer: {'fontFamily': 'GreatVibes_400Regular',color: '#FF668C'}, 
     leave: {'fontFamily': 'GreatVibes_400Regular',color: '#992E49'}, 
     bottom: { backgroundColor: '#D9A2A233'}, 
     dialer: {'fontFamily': 'GreatVibes_400Regular', fontSize: 16, color: '#FF4C79'}, 
     alpha: {'fontFamily': 'Poppins_400Regular',color: '#FF4C79'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#434C59'}, 
      quitbg: {backgroundColor: '#212D41'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF05'}, 
    searchi: {fontFamily: 'GreatVibes_400Regular', fontSize: 16,color: '#FFFFFF4D'}, 
    allappt: {fontFamily: 'GreatVibes_400Regular', fontSize: 18,color: '#FFFFFF'}, 
    allappi: {color: '#992E49'}, 
    header: {fontFamily: 'GreatVibes_400Regular', fontSize: 16,color: '#FFFFFF'}, 
    applist: {fontFamily: 'GreatVibes_400Regular', fontSize: 22,color: '#FF4D79'}, 
    applistbg: {borderColor: '#FFFFFF10', borderWidth: 1}, 
    appdu: {fontFamily: 'GreatVibes_400Regular', fontSize: 12,color: '#fff'}, 
    alphaside: {fontFamily: 'Poppins_400Regular',color: '#FF4D79'}, 
    tikbg: {backgroundColor: '#FFFFFF1A'},
    bubblebg: {backgroundColor: '#FF4C79',color: '#000000', shadowColor: '#00000080'},
// category
    searchCbg: {backgroundColor: '#FFFFFF05'}, 
    searchCi: {color: '#FF668C66'}, 
    searchCt: {fontFamily: 'GreatVibes_400Regular', fontSize: 18,color: '#FF668C66'}, 
    appC: {fontFamily: 'GreatVibes_400Regular', fontSize: 18,color: '#FFFFFF'}, 
    appi: {color: '#992E49'}, 
    appCn: {fontFamily: 'GreatVibes_400Regular', fontSize: 18,color: '#E6E6E6'}, 
    appCi: {color: '#E6E6E6'}, 
    applistC: {fontFamily: 'GreatVibes_400Regular', fontSize: 22,color: '#FF4D79'}, 
    applistCdu: {fontFamily: 'GreatVibes_400Regular', fontSize: 12,color: '#FFFFFF'}, 
    applistCbg: {backgroundColor: '',borderColor: '#FFFFFF10', borderWidth: 1}, 
    // block1
    block: {backgroundColor: '#131B27'},
    blockText1: {color: '#DBDFE5'},
    blockText2: {color: '#728099'},
    blockText3: {color: '#7FA8E5'},
    blockText4: {color: '#DBDFE5'},
    blockText5: {color: '#DBDFE5'},
    blockbg: {backgroundColor: '#ECF0FF'},
    blockgradient: ['#ECF0FF', '#7EA9E5'],
    blockcircle: {backgroundColor: '#5D8BCC'},
    blockbutton1: {backgroundColor: '#212C40'},
    blockbutton2: {backgroundColor: '#212C40'},
    blockbuttontext: {color: '#FFFFFF'},
    // block2
    blockText6: {color: '#DBDFE5'},
    blockText7: {color: '#DBDFE5'},
    blockText8: {color: '#728099'},
  //  weekly
    weeklytext1: {color: '#DBDFE5'},
    weeklytext2: {color: '#728099'},
    weekly2: {backgroundColor: '#212C40'},
 },
 9:{ //Wallpaper/10.jpg
   // home
     time: {'fontFamily': 'RubikScribble_400Regular', fontSize: 44,color: '#FFFFFF',},
     pm: {'fontFamily': 'Imprima_400Regular', fontSize: 16,color: '#FFFFFF',},
     date: {'fontFamily': 'Imprima_400Regular', fontSize: 16,color: '#FFFFFF',},
     battery: {color: '#FFFFFF'}, 
     home: {fontFamily: 'Imprima_400Regular', fontSize: 16,color: '#FFFFFF'}, 
     icon: { color: '#A2B9D9'}, 
     don: {'fontFamily': 'Imprima_400Regular',color: '#ffffff80',textShadowColor: '#000000ff', textShadowOffset: {width: 0, height: 0}, textShadowRadius: 1}, 
     footer: {'fontFamily': 'Imprima_400Regular',color: '#FFFFFF'}, 
     leave: {'fontFamily': 'Imprima_400Regular',color: '#FFFFFF70'}, 
     bottom: { backgroundColor: '#A2B9D933'}, 
     dialer: {'fontFamily': 'Imprima_400Regular', fontSize: 16, color: '#FFFFFF'}, 
     alpha: {'fontFamily': 'Poppins_400Regular',color: '#DADFE5'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#434C59'}, 
      quitbg: {backgroundColor: '#212D41'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF15'}, 
    searchi: {fontFamily: 'Imprima_400Regular', fontSize: 16,color: '#A2B9D940'}, 
    allappt: {fontFamily: 'Imprima_400Regular', fontSize: 16,color: '#FFFFFF'}, 
    allappi: {color: '#A2B9D9'}, 
    header: {fontFamily: 'Imprima_400Regular', fontSize: 16,color: '#FFFFFF'}, 
    applist: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#FFFFFF'}, 
    applistbg: {backgroundColor: '#0A223300'}, 
    appdu: {fontFamily: 'Poppins_400Regular', fontSize: 10,color: '#FFFFFF85'}, 
    alphaside: {fontFamily: 'Poppins_400Regular',color: '#DADFE5'}, 
    tikbg: {backgroundColor: '#FFFFFF26'},
    bubblebg: {backgroundColor: '#EFD897',color: '#192B33', shadowColor: '#000000'},
// category
    searchCbg: {backgroundColor: '#FFFFFF15'}, 
    searchCi: {color: '#A2B9D940'}, 
    searchCt: {fontFamily: 'Poppins_400Regular', fontSize: 16,color: '#A2B9D940'}, 
    appC: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#FFFFFF'}, 
    appi: {color: '#A2B9D9'}, 
    appCn: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#A2B9D9'}, 
    appCi: {color: '#A2B9D9'}, 
    applistC: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#FFFFFF'}, 
    applistCdu: {fontFamily: 'Imprima_400Regular', fontSize: 10,color: '#FFFFFF85'}, 
    applistCbg: {backgroundColor: '#0C121B00'},
    // block1
    block: {backgroundColor: '#131B27'},
    blockText1: {color: '#DBDFE5'},
    blockText2: {color: '#728099'},
    blockText3: {color: '#7FA8E5'},
    blockText4: {color: '#DBDFE5'},
    blockText5: {color: '#DBDFE5'},
    blockbg: {backgroundColor: '#ECF0FF'},
    blockgradient: ['#ECF0FF', '#7EA9E5'],
    blockcircle: {backgroundColor: '#5D8BCC'},
    blockbutton1: {backgroundColor: '#212C40'},
    blockbutton2: {backgroundColor: '#212C40'},
    blockbuttontext: {color: '#FFFFFF'},
    // block2
    blockText6: {color: '#DBDFE5'},
    blockText7: {color: '#DBDFE5'},
    blockText8: {color: '#728099'},
  //  weekly
    weeklytext1: {color: '#DBDFE5'},
    weeklytext2: {color: '#728099'},
    weekly2: {backgroundColor: '#212C40'}, 
 },
 10:{ //Wallpaper/11.jpg
      // home
     time: {'fontFamily': 'Goldman_400Regular', fontSize: 44,color: '#FF0080',},
     pm: {'fontFamily': 'UnicaOne_400Regular', fontSize: 16,color: '#FF0080',},
     date: {'fontFamily': 'UnicaOne_400Regular', fontSize: 16,color: '#FF0080',},
     battery: {color: '#FF0080'}, 
     home: {fontFamily: 'UnicaOne_400Regular', fontSize: 20,color: '#FF0080'}, 
     icon: { color: '#FF0080'}, 
     don: {'fontFamily': 'UnicaOne_400Regular',fontSize: 12,color: '#FF0080',textShadowColor: '#FFFFFF', textShadowOffset: {width: 1, height: 1}, textShadowRadius: 1}, 
     footer: {'fontFamily': 'UnicaOne_400Regular',fontSize: 16,color: '#FF0080', textShadowColor: '#FFFFFF', textShadowOffset: {width: 1, height: 1}, textShadowRadius: 1}, 
     leave: {'fontFamily': 'UnicaOne_400Regular',fontSize: 12,color: '#FF0080', textShadowColor: '#FFFFFF', textShadowOffset: {width: 1, height: 1}, textShadowRadius: 1}, 
     bottom: { backgroundColor: '#132C4D33',borderColor: '#D4CEFC80'}, 
     dialer: {'fontFamily': 'UnicaOne_400Regular', fontSize: 18, color: '#FF007F'}, 
     alpha: {'fontFamily': 'Poppins_400Regular',color: '#000000'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#434C59'}, 
      quitbg: {backgroundColor: '#212D41'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF1A'}, 
    searchi: {color: '#E6EBF260'}, 
    allappt: {fontFamily: 'UnicaOne_400Regular', fontSize: 18,color: '#FFFFFF'}, 
    allappi: {color: '#A2B9D9'}, 
    header: {fontFamily: 'Imprima_400Regular', fontSize: 16,color: '#FFFFFF'}, 
    applist: {fontFamily: 'UnicaOne_400Regular', fontSize: 18,color: '#FFFFFF'}, 
    applistbg: {backgroundColor: '#132C4D00'}, 
    appdu: {fontFamily: 'UnicaOne_400Regular', fontSize: 10,color: '#FFFFFF85'}, 
    alphaside: {fontFamily: 'Poppins_400Regular',color: '#DADFE5'}, 
    tikbg: {backgroundColor: '#FFFFFF1A'},
    wallbg: {backgroundColor: '#132C4D99'},
    bubblebg: {backgroundColor: '#C1CBD9',color: '#FF007F', shadowColor: '#0000004D'},
// category
    searchCbg: {backgroundColor: '#FFFFFF1A'}, 
    searchCi: {color: '#E6EBF260'}, 
    searchCt: {fontFamily: 'UnicaOne_400Regular', fontSize: 16,color: '#E6EBF260'}, 
    appC: {fontFamily: 'UnicaOne_400Regular', fontSize: 18,color: '#FFFFFF'}, 
    appi: {color: '#A2B9D9'}, 
    appCn: {fontFamily: 'Imprima_400Regular', fontSize: 14,color: '#FFFFFF'}, 
    appCi: {color: '#A2B9D9'}, 
    applistC: {fontFamily: 'UnicaOne_400Regular', fontSize: 18,color: '#FFFFFF'}, 
    applistCdu: {fontFamily: 'UnicaOne_400Regular', fontSize: 12,color: '#FFFFFF85'}, 
    applistCbg: {backgroundColor: '#132C4D00'}, 
    // block1
    block: {backgroundColor: '#131B27'},
    blockText1: {color: '#DBDFE5'},
    blockText2: {color: '#728099'},
    blockText3: {color: '#7FA8E5'},
    blockText4: {color: '#DBDFE5'},
    blockText5: {color: '#DBDFE5'},
    blockbg: {backgroundColor: '#ECF0FF'},
    blockgradient: ['#ECF0FF', '#7EA9E5'],
    blockcircle: {backgroundColor: '#5D8BCC'},
    blockbutton1: {backgroundColor: '#212C40'},
    blockbutton2: {backgroundColor: '#212C40'},
    blockbuttontext: {color: '#FFFFFF'},
    // block2
    blockText6: {color: '#DBDFE5'},
    blockText7: {color: '#DBDFE5'},
    blockText8: {color: '#728099'},
  //  weekly
    weeklytext1: {color: '#DBDFE5'},
    weeklytext2: {color: '#728099'},
    weekly2: {backgroundColor: '#212C40'}, 
 },
 11:{ //Wallpaper/12.jpg
       // home
     time: {'fontFamily': 'Caprasimo_400Regular', fontSize: 40,color: '#26E500',},
     pm: {'fontFamily': 'Gugi_400Regular', fontSize: 16,color: '#26E500',},
     date: {'fontFamily': 'Gugi_400Regular', fontSize: 14,color: '#26E500',},
     battery: {color: '#26E500'}, 
     home: {fontFamily: 'Gugi_400Regular', fontSize: 18,color: '#132C4D',}, 
     icon: { color: '#006618'}, 
     don: {'fontFamily': 'Gugi_400Regular',color: '#006618'}, 
     footer: {'fontFamily': 'Gugi_400Regular',color: '#132C4D'}, 
     leave: {'fontFamily': 'Gugi_400Regular',color: '#006618'}, 
     bottom: { backgroundColor: '#A2B9D933'}, 
     dialer: {'fontFamily': 'Gugi_400Regular', fontSize: 18, color: '#132C4D'}, 
     alpha: {'fontFamily': 'Poppins_400Regular',color: '#DADFE5'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#434C59'}, 
      quitbg: {backgroundColor: '#212D41'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF10'}, 
    searchi: {fontFamily: 'PlaywriteUSModern_400Regular', fontSize: 16,color: '#26E50033'}, 
    allappt: {fontFamily: 'Gugi_400Regular', fontSize: 16,color: '#26E500'}, 
    allappi: {color: '#26E500'}, 
    header: {fontFamily: 'Gugi_400Regular', fontSize: 16,color: '#26E500'}, 
    applist: {fontFamily: 'Gugi_400Regular', fontSize: 18,color: '#26E500'}, 
    applistbg: {backgroundColor: ''}, 
    appdu: {fontFamily: 'Poppins_400Regular', fontSize: 10,color: '#26E50085'}, 
    alphaside: {fontFamily: 'Poppins_400Regular',color: '#FFFFFF'}, 
    tikbg: {backgroundColor: '#FFFFFF1A'},
    wallbg: {backgroundColor: '#0C121BBF'},
    bubblebg: {backgroundColor: '#93FF80',color: '#192B33', shadowColor: '#0000004D'},
// category
    searchCbg: {backgroundColor: '#FFFFFF10'}, 
    searchCi: {color: '#26E50033'}, 
    searchCt: {fontFamily: 'PlaywriteUSModern_400Regular', fontSize: 16,color: '#26E50033'}, 
    appC: {fontFamily: 'Gugi_400Regular', fontSize: 18,color: '#26E500'}, 
    appi: {color: '#26E500'}, 
    appCn: {fontFamily: 'Gugi_400Regular', fontSize: 14,color: '#26E500'}, 
    appCi: {color: '#26E500'}, 
    applistC: {fontFamily: 'Gugi_400Regular', fontSize: 18,color: '#26E500'}, 
    applistCdu: {fontFamily: 'Poppins_400Regular', fontSize: 10,color: '#26E50085'}, 
    applistCbg: {backgroundColor: ''}, 
    // block1
    block: {backgroundColor: '#131B27'},
    blockText1: {color: '#DBDFE5'},
    blockText2: {color: '#728099'},
    blockText3: {color: '#7FA8E5'},
    blockText4: {color: '#DBDFE5'},
    blockText5: {color: '#DBDFE5'},
    blockbg: {backgroundColor: '#ECF0FF'},
    blockgradient: ['#ECF0FF', '#7EA9E5'],
    blockcircle: {backgroundColor: '#5D8BCC'},
    blockbutton1: {backgroundColor: '#212C40'},
    blockbutton2: {backgroundColor: '#212C40'},
    blockbuttontext: {color: '#FFFFFF'},
    // block2
    blockText6: {color: '#DBDFE5'},
    blockText7: {color: '#DBDFE5'},
    blockText8: {color: '#728099'},
  //  weekly
    weeklytext1: {color: '#DBDFE5'},
    weeklytext2: {color: '#728099'},
    weekly2: {backgroundColor: '#212C40'},
 },
 12:{//Wallpaper/13.jpg
   // home
     time: {'fontFamily': 'RubikMoonrocks_400Regular', fontSize: 50,color: '#FF59A5',},
     pm: {'fontFamily': 'LobsterTwo_400Regular', fontSize: 16,color: '#FF59A5',},
     date: {'fontFamily': 'LobsterTwo_400Regular', fontSize: 13,color: '#FF59A5',},
     battery: {color: '#FF59A5'}, 
     home: {fontFamily: 'LobsterTwo_400Regular', fontSize: 18,color: '#FF59A5',textShadowColor: '#FFF', textShadowOffset: {width: 4, height: 4}, textShadowRadius: 4}, 
     icon: { color: '#FF59A5'}, 
     don: {'fontFamily': 'LobsterTwo_400Regular',color: '#FEB3CF'}, 
     footer: {'fontFamily': 'LobsterTwo_400Regular',color: '#FF59A5'}, 
     leave: {'fontFamily': 'LobsterTwo_400Regular',color: '#FEB3CF'}, 
     bottom: { backgroundColor: '#ffffff40',borderColor: '#FEC2FE33',borderWidth: 1}, 
     dialer: {'fontFamily': 'LobsterTwo_400Regular', fontSize: 18, color: '#FF59A5'}, 
     alpha: {'fontFamily': 'Poppins_400Regular',color: '#FF59A5'}, 
    //  modal
    modalbg: {backgroundColor: '#FFFFFF'}, 
      open: {color: '#2E3A4C'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#FF59A5'}, 
      number: {color: '#FFFFFF'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#CC4784'}, 
      when: {color: '#2E3B4D'}, 
      remind: {color: '#2E3B4D'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#A2B9D9'}, 
      quitbg: {backgroundColor: '#CC4784'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF10'}, 
    searchi: {color: '#FF59A533'}, 
    allappt: {fontFamily: 'LobsterTwo_400Regular', fontSize: 16,color: '#FF59A5'}, 
    allappi: {color: '#FF59A5'}, 
    header: {fontFamily: 'LobsterTwo_400Regular', fontSize: 16,color: '#FF59A5'}, 
    applist: {fontFamily: 'LobsterTwo_400Regular', fontSize: 18,color: '#FF59A5'}, 
    applistbg: {backgroundColor: '#FF59A50D'}, 
    appdu: {fontFamily: 'LobsterTwo_400Regular', fontSize: 10,color: '#FF59A5'}, 
    alphaside: {fontFamily: 'Poppins_400Regular',color: '#FF59A5'}, 
    tikbg: {backgroundColor: '#FFFFFF40'},
    wallbg: {backgroundColor: ''},
    bubblebg: {backgroundColor: '#FE57A5',color: '#192B33', shadowColor: '#0000004D'},
// category
    searchCbg: {backgroundColor: '#FFFFFF10'}, 
    searchCi: {color: '#FF59A533'}, 
    searchCt: {fontFamily: 'LobsterTwo_400Regular', fontSize: 16,color: '#FF59A533'}, 
    appC: {fontFamily: 'LobsterTwo_400Regular', fontSize: 18,color: '#FF59A5'}, 
    appi: {color: '#FF59A5'}, 
    appCn: {fontFamily: 'LobsterTwo_400Regular', fontSize: 14,color: '#FF59A5'}, 
    appCi: {color: '#FF59A5'}, 
    applistC: {fontFamily: 'LobsterTwo_400Regular', fontSize: 18,color: '#FF59A5'}, 
    applistCdu: {fontFamily: 'LobsterTwo_400Regular', fontSize: 10,color: '#FF59A5'}, 
    applistCbg: {backgroundColor: '#FF59A50D'}, 
    // block1
    block: {backgroundColor: '#FFFFFF'},
    blockText1: {color: '#2E3B4D'},
    blockText2: {color: '#858E9D'},
    blockText3: {color: '#8698B2'},
    blockText4: {color: '#2E3B4D'},
    blockText5: {color: '#2E3B4D'},
    blockbg: {backgroundColor: '#ECF0FF'},
    blockgradient: ['#ECF0FF', '#FF59A5'],
    blockcircle: {backgroundColor: '#CC4784'},
    blockbutton1: {backgroundColor: '#FF59A5'},
    blockbutton2: {backgroundColor: '#CC4784'},
    blockbuttontext: {color: '#FFFFFF'},
    // block2
    blockText6: {color: '#2E3B4D'},
    blockText7: {color: '#2E3B4D'},
    blockText8: {color: '#858E9D'},
  //  weekly
    weeklytext1: {color: '#2F3A4D'},
    weeklytext2: {color: '#89A2CA'},
    weekly2: {backgroundColor: '#FF59A5'},
 },
 13:{//Wallpaper/14.jpg
     // home
     time: {'fontFamily': 'DynaPuff_400Regular', fontSize: 44,color: '#A37ACC',},
     pm: {'fontFamily': 'DynaPuff_400Regular', fontSize: 16,color: '#A37ACC',},
     date: {'fontFamily': 'DynaPuff_400Regular', fontSize: 13,color: '#A37ACC',},
     battery: {color: '#A37ACC'}, 
     home: {fontFamily: 'DynaPuff_400Regular', fontSize: 18,color: '#A37ACC',}, 
     icon: { color: '#D4CEFE'}, 
     don: {'fontFamily': 'DynaPuff_400Regular',color: '#D4CEFE'}, 
     footer: {'fontFamily': 'DynaPuff_400Regular',color: '#9772BF'}, 
     leave: {'fontFamily': 'DynaPuff_400Regular',color: '#9772BF'}, 
     bottom: { backgroundColor: '#D4CEFC33',borderColor: '#D4CEFC80',borderWidth: 1}, 
     dialer: {'fontFamily': 'Imprima_400Regular', fontSize: 16, color: '#A37ACC'}, 
     alpha: {'fontFamily': 'Poppins_400Regular',color: '#A37ACC'}, 
    //  modal
    modalbg: {backgroundColor: '#FFF'}, 
      open: {color: '#2E3A4C'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#A37ACC'}, 
      number: {color: '#FFFFFF'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#A37ACC'}, 
      when: {color: '#2E3B4D'}, 
      remind: {color: '#2E3B4D'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#A37ACC'}, 
      quitbg: {backgroundColor: '#A37ACC'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF40'}, 
    searchi: {color: '#B781CF40'}, 
    allappt: {fontFamily: 'DynaPuff_400Regular', fontSize: 16,color: '#A37ACC'}, 
    allappi: {color: '#9570BD'}, 
    header: {fontFamily: 'DynaPuff_400Regular', fontSize: 16,color: '#A37ACC'}, 
    applist: {fontFamily: 'DynaPuff_400Regular', fontSize: 18,color: '#A37ACC'}, 
    applistbg: {backgroundColor: '#D4CEFC33'}, 
    appdu: {fontFamily: 'Imprima_400Regular', fontSize: 10,color: '#B781CF'}, 
    alphaside: {fontFamily: 'Poppins_400Regular',color: '#A37ACC'}, 
    tikbg: {backgroundColor: '#FFFFFF40'},
    wallbg: {backgroundColor: ''},
    bubblebg: {backgroundColor: '#F8EDFF',color: '#192B33', shadowColor: '#0000004D'},
// category
    searchCbg: {backgroundColor: '#FFFFFF40'}, 
    searchCi: {color: '#B781CF40'}, 
    searchCt: {fontFamily: 'Poppins_400Regular', fontSize: 16,color: '#B781CF40'}, 
    appC: {fontFamily: 'DynaPuff_400Regular', fontSize: 18,color: '#A37ACC'}, 
    appi: {color: '#9570BD'}, 
    appCn: {fontFamily: 'DynaPuff_400Regular', fontSize: 14,color: '#A37ACC'}, 
    appCi: {color: '#A37ACC'}, 
    applistC: {fontFamily: 'DynaPuff_400Regular', fontSize: 18,color: '#A37ACC'}, 
    applistCdu: {fontFamily: 'Imprima_400Regular', fontSize: 12,color: '#B781CF'}, 
    applistCbg: {backgroundColor: '#D4CEFC33'}, 
    // block1
    block: {backgroundColor: '#FFFFFF'},
    blockText1: {color: '#2E3B4D'},
    blockText2: {color: '#858E9D'},
    blockText3: {color: '#8698B2'},
    blockText4: {color: '#2E3B4D'},
    blockText5: {color: '#2E3B4D'},
    blockbg: {backgroundColor: '#ECF0FF'},
    blockgradient: ['#ECF0FF', '#A37ACC'],
    blockcircle: {backgroundColor: '#896CA6'},
    blockbutton1: {backgroundColor: '#A37ACC'},
    blockbutton2: {backgroundColor: '#896CA6'},
    blockbuttontext: {color: '#FFFFFF'},
    // block2
    blockText6: {color: '#2E3B4D'},
    blockText7: {color: '#2E3B4D'},
    blockText8: {color: '#858E9D'},
  //  weekly
    weeklytext1: {color: '#DBDFE5'},
    weeklytext2: {color: '#728099'},
    weekly2: {backgroundColor: '#A37ACC'},
 },
 14:{ //Wallpaper/15.jpg
  
  // home
     time: {'fontFamily': 'Shizuru_400Regular', fontSize: 48,color: '#FFFFFF',},
     pm: {'fontFamily': 'Gugi_400Regular', fontSize: 12,color: '#FFFFFF',},
     date: {'fontFamily': 'Gugi_400Regular', fontSize: 12,color: '#FFFFFF',},
     battery: {color: '#FF0000'}, 
     home: {fontFamily: 'MontserratAlternates_400Regular', fontSize: 16,color: '#FFFFFF',}, 
     icon: { color: '#FF8080'}, 
     don: {'fontFamily': 'MontserratAlternates_400Regular',color: '#FF8080'}, 
     footer: {'fontFamily': 'MontserratAlternates_400Regular',color: '#FFFFFF'}, 
     leave: {'fontFamily': 'MontserratAlternates_400Regular',color: '#FF8080'}, 
     bottom: { backgroundColor: '#FF000133'}, 
     dialer: {'fontFamily': 'MontserratAlternates_400Regular', fontSize: 16, color: '#FFFFFF'}, 
     alpha: {'fontFamily': 'Poppins_400Regular',color: '#DADFE5'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#434C59'}, 
      quitbg: {backgroundColor: '#212D41'}, 
    //  allApps
    searchbg: {backgroundColor: '#FF000120'}, 
    searchi: {fontFamily: 'Poppins_400Regular', fontSize: 16,color: '#FFFFFF40'}, 
    allappt: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#FFFFFF'}, 
    allappi: {color: '#FF0000'}, 
    header: {fontFamily: 'Imprima_400Regular', fontSize: 16,color: '#FFFFFF'}, 
    applist: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#FFFFFF'}, 
    applistbg: {backgroundColor: '#FF000180'}, 
    appdu: {fontFamily: 'Poppins_400Regular', fontSize: 10,color: '#FF8080'}, 
    alphaside: {fontFamily: 'Poppins_400Regular',color: '#FFFFFF'}, 
    tikbg: {backgroundColor: '#FF000140'},
    wallbg: {backgroundColor: '#0C121B80'},
    bubblebg: {backgroundColor: '#FF8082',color: '#000000', shadowColor: '#0000004D'},
// category
    searchCbg: {backgroundColor: '#FF000120'}, 
    searchCi: {color: '#FFFFFF40'}, 
    searchCt: {fontFamily: 'Imprima_400Regular', fontSize: 16,color: '#FFFFFF40'}, 
    appC: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#FFFFFF'}, 
    appi: {color: '#FF0000'}, 
    appCn: {fontFamily: 'Imprima_400Regular', fontSize: 14,color: '#FF0000'}, 
    appCi: {color: '#FF0000'}, 
    applistC: {fontFamily: 'Imprima_400Regular', fontSize: 18,color: '#FFFFFF'}, 
    applistCdu: {fontFamily: 'Poppins_400Regular', fontSize: 10,color: '#FF8080'}, 
    applistCbg: {backgroundColor: '#FF000180'},
    // block1
    block: {backgroundColor: '#131B27'},
    blockText1: {color: '#DBDFE5'},
    blockText2: {color: '#728099'},
    blockText3: {color: '#7FA8E5'},
    blockText4: {color: '#DBDFE5'},
    blockText5: {color: '#DBDFE5'},
    blockbg: {backgroundColor: '#ECF0FF'},
    blockgradient: ['#ECF0FF', '#7EA9E5'],
    blockcircle: {backgroundColor: '#5D8BCC'},
    blockbutton1: {backgroundColor: '#212C40'},
    blockbutton2: {backgroundColor: '#212C40'},
    blockbuttontext: {color: '#FFFFFF'},
    // block2
    blockText6: {color: '#DBDFE5'},
    blockText7: {color: '#DBDFE5'},
    blockText8: {color: '#728099'},
  //  weekly
    weeklytext1: {color: '#DBDFE5'},
    weeklytext2: {color: '#728099'},
    weekly2: {backgroundColor: '#212C40'},
 },
 15:{ //Wallpaper/16.jpg
    // home
     time: {'fontFamily': 'Dangrek_400Regular', fontSize: 50,color: '#FF9500',},
     pm: {'fontFamily': 'MontserratAlternates_400Regular', fontSize: 14,color: '#FF9500',},
     date: {'fontFamily': 'MontserratAlternates_400Regular', fontSize: 14,color: '#FF9500',},
     battery: {color: '#FF9500'}, 
     home: {fontFamily: 'MontserratAlternates_400Regular', fontSize: 16,color: '#FF9500',}, 
     icon: { color: '#808080'}, 
     don: {'fontFamily': 'MontserratAlternates_400Regular',color: '#808080'}, 
     footer: {'fontFamily': 'MontserratAlternates_400Regular',color: '#FF9500'}, 
     leave: {'fontFamily': 'MontserratAlternates_400Regular',color: '#808080'}, 
     bottom: { backgroundColor: '#A2B9D933'}, 
     dialer: {'fontFamily': 'MontserratAlternates_400Regular', fontSize: 18, color: '#FFFFFF'}, 
     camera: {'fontFamily': 'MontserratAlternates_400Regular', fontSize: 18, color: '#031017'}, 
     alpha: {'fontFamily': 'Poppins_400Regular',fontSize: 16,color: '#132C4D'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#FF9500'}, 
      number: {color: '#132C4D'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#FF9500'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#FF9500'}, 
      quitbg: {backgroundColor: '#FF9500'}, 
    //  allApps
    searchbg: {backgroundColor: '#FFFFFF10'}, 
    searchi: {fontFamily: 'Poppins_400Regular', fontSize: 16,color: '#A2B9D9'}, 
    allappt: {fontFamily: 'Comfortaa_400Regular', fontSize: 16,color: '#FFFFFF'}, 
    allappi: {color: '#132C4D'}, 
    header: {fontFamily: 'Comfortaa_400Regular', fontSize: 16,color: '#FFFFFF'}, 
    applist: {fontFamily: 'Comfortaa_400Regular', fontSize: 16,color: '#FFFFFF'}, 
    applistbg: {backgroundColor: '#FFFFFF00'}, 
    appdu: {fontFamily: 'Poppins_400Regular', fontSize: 10,color: '#FFFFFF70'}, 
    alphaside: {fontFamily: 'Poppins_400Regular',color: '#132C4D'}, 
    tikbg: {backgroundColor: '#FFFFFF1A'},
    wallbg: {backgroundColor: ''},
    bubblebg: {backgroundColor: '#FFA754',color: '#FFFFFF', shadowColor: '#0000001A'},
// category
    searchCbg: {backgroundColor: '#FFFFFF10'}, 
    searchCi: {color: '#A2B9D9'}, 
    searchCt: {fontFamily: 'Poppins_400Regular', fontSize: 16,color: '#A2B9D9'}, 
    appC: {fontFamily: 'Comfortaa_400Regular', fontSize: 18,color: '#FFFFFF'}, 
    appi: {color: '#132C4D'}, 
    appCn: {fontFamily: 'Poppins_400Regular', fontSize: 14,color: '#132C4D'}, 
    appCi: {color: '#132C4D'}, 
    applistC: {fontFamily: 'Comfortaa_400Regular', fontSize: 16,color: '#FFFFFF'}, 
    applistCdu: {fontFamily: 'Poppins_400Regular', fontSize: 10,color: '#FFFFFF70'}, 
    applistCbg: {backgroundColor: '#FFFFFF00'},
    // block1
    block: {backgroundColor: '#131B27'},
    blockText1: {color: '#DBDFE5'},
    blockText2: {color: '#728099'},
    blockText3: {color: '#7FA8E5'},
    blockText4: {color: '#DBDFE5'},
    blockText5: {color: '#DBDFE5'},
    blockbg: {backgroundColor: '#ECF0FF'},
    blockgradient: ['#ECF0FF', '#FF9500'],
    blockcircle: {backgroundColor: '#E58E39'},
    blockbutton1: {backgroundColor: '#FF9500'},
    blockbutton2: {backgroundColor: '#FF9500'},
    blockbuttontext: {color: '#000000'},
    // block2
    blockText6: {color: '#DBDFE5'},
    blockText7: {color: '#DBDFE5'},
    blockText8: {color: '#728099'},
  //  weekly
    weeklytext1: {color: '#DBDFE5'},
    weeklytext2: {color: '#728099'},
    weekly2: {backgroundColor: '#FF9500'},
 },
 16:{ //Wallpaper/17.jpg
    // home
     time: {'fontFamily': 'RobotoSlab_400Regular', fontSize: 48,color: '#FFFFFF',},
     pm: {'fontFamily': 'RobotoSlab_400Regular', fontSize: 18,color: '#FFFFFF',},
     date: {'fontFamily': 'RobotoSlab_400Regular', fontSize: 18,color: '#FFFFFF',},
     battery: {color: '#FFFFFF'}, 
     home: {fontFamily: 'CourierPrime_700Bold', fontSize: 18,color: '#FFFFFF',}, 
     icon: { color: '#FFFFFF'}, 
     don: {'fontFamily': 'CourierPrime_400Regular',color: '#FFFFFF'}, 
     footer: {'fontFamily': 'CourierPrime_700Bold', fontSize: 12,color: '#FFFFFF'}, 
     leave: {'fontFamily': 'CourierPrime_400Regular',fontSize: 10,color: '#FFFFFF'}, 
     bottom: { backgroundColor: '#000000',borderWidth: 1,borderColor: '#FFFFFF50'},   
     dialer: {'fontFamily': 'CourierPrime_700Bold', fontSize: 18, color: '#FFFFFF'}, 
     alpha: {'fontFamily': 'CourierPrime_400Regular',fontSize: 12,color: '#808080'}, 
    //  modal
     modalbg: {backgroundColor: '#000000'}, 
      open: {'fontFamily': 'CourierPrime_700Bold',color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {'fontFamily': 'CourierPrime_700Bold',color: '#fff'}, 
      numberbg: {backgroundColor: '',borderWidth: 1,borderColor: '#FFFFFF50'}, 
      number: {'fontFamily': 'CourierPrime_700Bold',fontSize:20,color: '#DBDFE5'}, 
      toggle: {color: '#fff'}, 
      togglei: {color: '#fff'}, 
      when: {'fontFamily': 'CourierPrime_700Bold',color: '#fff'}, 
      remind: {'fontFamily': 'CourierPrime_700Bold',color: '#fff'}, 
      quit: {'fontFamily': 'CourierPrime_700Bold',fontSize: 20,color: '#FFFFFF'}, 
      bordert: {borderColor: '#ffffff50'}, 
      quitbg: {backgroundColor: '',borderWidth: 1,borderColor: '#FFFFFF50'},
    //  allApps
    searchbg: {backgroundColor: ''}, 
    searchi: {fontFamily: 'Poppins_400Regular', fontSize: 16,color: '#FFFFFF80'}, 
    allappt: {fontFamily: 'CourierPrime_700Bold', fontSize: 20,color: '#FFFFFF'}, 
    allappi: {color: '#808080'}, 
    header: {fontFamily: 'CourierPrime_400Regular', fontSize: 16,color: '#FFFFFF'}, 
    applist: {fontFamily: 'CourierPrime_700Bold', fontSize: 18,color: '#FFFFFF'}, 
    applistbg: {backgroundColor: '',borderWidth: 1,borderColor: '#FFFFFF50'}, 
    appdu: {fontFamily: 'RobotoSlab_400Regular', fontSize: 10,color: '#FFFFFF'}, 
    alphaside: {fontFamily: 'CourierPrime_400Regular',color: '#949494'}, 
    tikbg: {backgroundColor: '#FFFFFF1A'},
    wallbg: {backgroundColor: ''},
    bubblebg: {backgroundColor: '#FFFFFF',color: '#192B33', shadowColor: '#FFFFFF40'},
// category
    searchCbg: {backgroundColor: ''}, 
    searchCi: {color: '#FFFFFF80'}, 
    searchCt: {fontFamily: 'CourierPrime_400Regular', fontSize: 16,color: '#FFFFFF80'}, 
    appC: {fontFamily: 'CourierPrime_700Bold', fontSize: 18,color: '#FFFFFF'}, 
    appi: {color: '#FFFFFF80'}, 
    appCn: {fontFamily: 'CourierPrime_400Regular', fontSize: 16,color: '#FFFFFF'}, 
    appCi: {color: '#808080'}, 
    applistC: {fontFamily: 'CourierPrime_700Bold', fontSize: 18,color: '#FFFFFF'}, 
    applistCdu: {fontFamily: 'RobotoSlab_400Regular', fontSize: 10,color: '#FFFFFF'}, 
    applistCbg: {backgroundColor: '',borderWidth: 1,borderColor: '#FFFFFF50'},
    // block1
    block: {backgroundColor: '#131B27'},
    blockText1: {color: '#DBDFE5'},
    blockText2: {color: '#728099'},
    blockText3: {color: '#7FA8E5'},
    blockText4: {color: '#DBDFE5'},
    blockText5: {color: '#DBDFE5'},
    blockbg: {backgroundColor: '#ECF0FF'},
    blockgradient: ['#ECF0FF', '#7EA9E5'],
    blockcircle: {backgroundColor: '#5D8BCC'},
    blockbutton1: {backgroundColor: '#212C40'},
    blockbutton2: {backgroundColor: '#212C40'},
    blockbuttontext: {color: '#FFFFFF'},
    // block2
    blockText6: {color: '#DBDFE5'},
    blockText7: {color: '#DBDFE5'},
    blockText8: {color: '#728099'},
  //  weekly
    weeklytext1: {color: '#DBDFE5'},
    weeklytext2: {color: '#728099'},
    weekly2: {backgroundColor: '#212C40'},
 },
 
 17:{ //Wallpaper/18.jpg
    // home
     time: {'fontFamily': 'RobotoSlab_400Regular', fontSize: 48,color: '#000000',},
     pm: {'fontFamily': 'RobotoSlab_400Regular', fontSize: 18,color: '#000000',},
     date: {'fontFamily': 'RobotoSlab_400Regular', fontSize: 18,color: '#000000',},
     battery: {color: '#000000'}, 
     home: {fontFamily: 'CourierPrime_700Bold', fontSize: 18,color: '#000000',}, 
     icon: { color: '#000000'}, 
     don: {'fontFamily': 'CourierPrime_400Regular',color: '#000000'}, 
     footer: {'fontFamily': 'CourierPrime_700Bold', fontSize: 12,color: '#000000'}, 
     leave: {'fontFamily': 'CourierPrime_400Regular',fontSize: 10,color: '#000000'}, 
     bottom: { backgroundColor: '',borderWidth: 1,borderColor: '#00000050'},   
     dialer: {'fontFamily': 'CourierPrime_700Bold', fontSize: 18, color: '#000000'}, 
     alpha: {'fontFamily': 'CourierPrime_400Regular',fontSize: 16,color: '#000000'}, 
    //  modal
     modalbg: {backgroundColor: '#fff'}, 
      open: {'fontFamily': 'CourierPrime_700Bold',color: '#000000'}, 
      appicon: {color: '#1A2B33'}, 
      select: {'fontFamily': 'CourierPrime_700Bold',color: '#000000'}, 
      numberbg: {backgroundColor: '',borderWidth: 1,borderColor: '#00000050'}, 
      number: {'fontFamily': 'CourierPrime_700Bold',fontSize:20,color: '#000000'}, 
      toggle: {color: '#000000'}, 
      togglei: {color: '#000000'}, 
      when: {'fontFamily': 'CourierPrime_700Bold',color: '#000000'}, 
      remind: {'fontFamily': 'CourierPrime_700Bold',color: '#000000'}, 
      quit: {'fontFamily': 'CourierPrime_700Bold',fontSize: 20,color: '#000000'}, 
      bordert: {borderColor: '#00000050'}, 
      quitbg: {backgroundColor: '',borderWidth: 1,borderColor: '#00000050'},
    //  allApps
    searchbg: {borderColor: '#00000080'}, 
    searchi: {fontFamily: 'Poppins_400Regular', fontSize: 16,color: '#00000080'}, 
    allappt: {fontFamily: 'CourierPrime_700Bold', fontSize: 20,color: '#000000'}, 
    allappi: {color: '#808080'}, 
    header: {fontFamily: 'CourierPrime_400Regular', fontSize: 16,color: '#000000'}, 
    applist: {fontFamily: 'CourierPrime_700Bold', fontSize: 18,color: '#000000'}, 
    applistbg: {backgroundColor: '',borderWidth: 1,borderColor: '#00000050'}, 
    appdu: {fontFamily: 'RobotoSlab_400Regular', fontSize: 10,color: '#000000'}, 
    alphaside: {fontFamily: 'CourierPrime_400Regular',color: '#949494'}, 
    tikbg: {backgroundColor: '#0000001A'},
    wallbg: {backgroundColor: ''},
    bubblebg: {backgroundColor: '#000000',color: '#FFFFFF', shadowColor: '#0000004D'},
// category
    searchCbg: {borderColor: '#00000080',backgroundColor: ''}, 
    searchCi: {color: '#00000080'}, 
    searchCt: {fontFamily: 'CourierPrime_400Regular', fontSize: 16,color: '#00000080'}, 
    appC: {fontFamily: 'CourierPrime_700Bold', fontSize: 18,color: '#000000'}, 
    appi: {color: '#00000080'}, 
    appCn: {fontFamily: 'CourierPrime_400Regular', fontSize: 16,color: '#000000'}, 
    appCi: {color: '#808080'}, 
    applistC: {fontFamily: 'CourierPrime_700Bold', fontSize: 18,color: '#000000'}, 
    applistCdu: {fontFamily: 'RobotoSlab_400Regular', fontSize: 10,color: '#000000'}, 
    applistCbg: {backgroundColor: '',borderWidth: 1,borderColor: '#00000050'},
   // block1
    block: {backgroundColor: '#131B27'},
    blockText1: {color: '#DBDFE5'},
    blockText2: {color: '#728099'},
    blockText3: {color: '#7FA8E5'},
    blockText4: {color: '#DBDFE5'},
    blockText5: {color: '#DBDFE5'},
    blockbg: {backgroundColor: '#ECF0FF'},
    blockgradient: ['#ECF0FF', '#7EA9E5'],
    blockcircle: {backgroundColor: '#5D8BCC'},
    blockbutton1: {backgroundColor: '#212C40'},
    blockbutton2: {backgroundColor: '#212C40'},
    blockbuttontext: {color: '#FFFFFF'},
    // block2
    blockText6: {color: '#DBDFE5'},
    blockText7: {color: '#DBDFE5'},
    blockText8: {color: '#728099'},
  //  weekly
    weeklytext1: {color: '#DBDFE5'},
    weeklytext2: {color: '#728099'},
    weekly2: {backgroundColor: '#212C40'},
 },
 18:{ //Wallpaper/19.jpg
      // home
     time: {'fontFamily': 'Poppins_400Regular', fontSize: 40,color: '#DADFE5',},
     pm: {'fontFamily': 'Poppins_400Regular', fontSize: 14,color: '#DADFE5',},
     date: {'fontFamily': 'Poppins_400Regular', fontSize: 14,color: '#728099',},
     battery: {color: '#7FA8E5'}, 
     home: {fontFamily: 'Poppins_400Regular', fontSize: 16,color: '#DADFE5',}, 
     icon: { color: '#738099'}, 
     don: {'fontFamily': 'Poppins_400Regular',color: '#434C59'}, 
     footer: {'fontFamily': 'Poppins_400Regular',color: '#DADFE5'}, 
     leave: {'fontFamily': 'Poppins_400Regular',color: '#738099'}, 
     bottom: { backgroundColor: '#131B2680'}, 
     dialer: {'fontFamily': 'Poppins_400Regular', fontSize: 18, color: '#DADFE5'}, 
     alpha: {'fontFamily': 'Poppins_400Regular',color: '#738099'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#434C59'}, 
      quitbg: {backgroundColor: '#212D41'}, 
    //  allApps
    searchbg: {backgroundColor: ''}, 
    searchi: {fontFamily: 'Poppins_400Regular', fontSize: 16,color: '#434C59'}, 
    allappt: {fontFamily: 'Poppins_400Regular', fontSize: 16,color: '#DADFE5'}, 
    allappi: {color: '#728099'}, 
    header: {fontFamily: 'Poppins_400Regular', fontSize: 16,color: '#728099'}, 
    applist: {fontFamily: 'Poppins_400Regular', fontSize: 18,color: '#DADFE5'}, 
    applistbg: {backgroundColor: ''}, 
    appdu: {fontFamily: 'Poppins_400Regular', fontSize: 10,color: '#FFFFFF50'}, 
    alphaside: {fontFamily: 'Poppins_400Regular',color: '#738099'}, 
    tikbg: {backgroundColor: '#FFFFFF1A'},
    wallbg: {backgroundColor: ''},
    bubblebg: {backgroundColor: '#7A90A7',color: '#000000', shadowColor: '#FFFFFF33'},
// category
    searchCbg: {backgroundColor: ''}, 
    searchCi: {color: '#434C59'}, 
    searchCt: {fontFamily: 'Poppins_400Regular', fontSize: 16,color: '#434C59'}, 
    appC: {fontFamily: 'Poppins_400Regular', fontSize: 18,color: '#DBDFE4'}, 
    appi: {color: '#728099'}, 
    appCn: {fontFamily: 'Poppins_400Regular', fontSize: 14,color: '#728099'}, 
    appCi: {color: '#858E9D'}, 
    applistC: {fontFamily: 'Poppins_400Regular', fontSize: 18,color: '#DBDFE5'}, 
    applistCdu: {fontFamily: 'Poppins_400Regular', fontSize: 10,color: '#FFFFFF50'}, 
    applistCbg: {backgroundColor: ''}, 
     // block1
    block: {backgroundColor: '#131B27'},
    blockText1: {color: '#DBDFE5'},
    blockText2: {color: '#728099'},
    blockText3: {color: '#7FA8E5'},
    blockText4: {color: '#DBDFE5'},
    blockText5: {color: '#DBDFE5'},
    blockbg: {backgroundColor: '#ECF0FF'},
    blockgradient: ['#ECF0FF', '#7EA9E5'],
    blockcircle: {backgroundColor: '#5D8BCC'},
    blockbutton1: {backgroundColor: '#212C40'},
    blockbutton2: {backgroundColor: '#212C40'},
    blockbuttontext: {color: '#FFFFFF'},
    // block2
    blockText6: {color: '#DBDFE5'},
    blockText7: {color: '#DBDFE5'},
    blockText8: {color: '#728099'},
  //  weekly
    weeklytext1: {color: '#DBDFE5'},
    weeklytext2: {color: '#728099'},
    weekly2: {backgroundColor: '#212C40'},
 },
 19:{ //Wallpaper/20.jpg
         // home
     time: {'fontFamily': 'Frijole_400Regular', fontSize: 48,color: '#E8E04B', textShadowColor: '#00D37B', textShadowOffset: { width: 4, height: 4 }, textShadowRadius: 20},
     pm: {'fontFamily': 'Pacifico_400Regular', fontSize: 14,color: '#E8E04B',},
     date: {'fontFamily': 'Pacifico_400Regular', fontSize: 14,color: '#E8E04B',},
     battery: {color: '#7FA8E5'}, 
     home: {fontFamily: 'Pacifico_400Regular', fontSize: 16,color: '#E8E04B',}, 
     icon: { color: '#E8DF4B'}, 
     don: {'fontFamily': 'Pacifico_400Regular',color: '#868242'}, 
     footer: {'fontFamily': 'Pacifico_400Regular',color: '#E8DF4B'}, 
     leave: {'fontFamily': 'Pacifico_400Regular',color: '#868242'}, 
     bottom: { backgroundColor: '#131B2680'}, 
     dialer: {'fontFamily': 'Pacifico_400Regular', fontSize: 18, color: '#E8DF4B'}, 
     alpha: {'fontFamily': 'Pacifico_400Regular',color: '#000000'}, 
    //  modal
    modalbg: {backgroundColor: '#131B27'}, 
      open: {color: '#DBDFE5'}, 
      appicon: {color: '#1A2B33'}, 
      select: {color: '#A3B8D9'}, 
      numberbg: {backgroundColor: '#212C40'}, 
      number: {color: '#DBDFE5'}, 
      toggle: {color: '#2E3B4D'}, 
      togglei: {color: '#5C8BCC'}, 
      when: {color: '#FFFFFF'}, 
      remind: {color: '#FFFFFF'}, 
      quit: {color: '#FFFFFF'}, 
      bordert: {borderColor: '#434C59'}, 
      quitbg: {backgroundColor: '#212D41'}, 
    //  allApps
    searchbg: {backgroundColor: ''}, 
    searchi: {fontFamily: 'Pacifico_400Regular', fontSize: 16,color: '#868242'}, 
    allappt: {fontFamily: 'Pacifico_400Regular', fontSize: 18,color: '#E8E04B'}, 
    allappi: {color: '#868242'}, 
    header: {fontFamily: 'Pacifico_400Regular', fontSize: 16,color: '#868242'}, 
    applist: {fontFamily: 'Pacifico_400Regular', fontSize: 18,color: '#E8E04B'}, 
    applistbg: {backgroundColor: ''}, 
    appdu: {fontFamily: 'Poppins_400Regular', fontSize: 10,color: '#FFFFFF50'}, 
    alphaside: {fontFamily: 'Poppins_400Regular',color: '#738099'}, 
    tikbg: {backgroundColor: '#FFFFFF1A'},
    wallbg: {backgroundColor: ''},
    bubblebg: {backgroundColor: '#044879',color: '#728099', shadowColor: '#0000001A'},
// category
    searchCbg: {backgroundColor: ''}, 
    searchCi: {color: '#868242'}, 
    searchCt: {fontFamily: 'Pacifico_400Regular', fontSize: 17,color: '#86824280'}, 
    appC: {fontFamily: 'Pacifico_400Regular', fontSize: 18,color: '#E8E04B'}, 
    appi: {color: '#B6B058'}, 
    appCn: {fontFamily: 'Pacifico_400Regular', fontSize: 14,color: '#B6B058'}, 
    appCi: {color: '#868242'}, 
    applistC: {fontFamily: 'Pacifico_400Regular', fontSize: 18,color: '#E8E04B'}, 
    applistCdu: {fontFamily: 'Poppins_400Regular', fontSize: 10,color: '#FFFFFF50'}, 
    applistCbg: {backgroundColor: ''}, 
    // block1
    block: {backgroundColor: '#131B27'},
    blockText1: {color: '#DBDFE5'},
    blockText2: {color: '#728099'},
    blockText3: {color: '#7FA8E5'},
    blockText4: {color: '#DBDFE5'},
    blockText5: {color: '#DBDFE5'},
    blockbg: {backgroundColor: '#ECF0FF'},
    blockgradient: ['#ECF0FF', '#7EA9E5'],
    blockcircle: {backgroundColor: '#5D8BCC'},
    blockbutton1: {backgroundColor: '#212C40'},
    blockbutton2: {backgroundColor: '#212C40'},
    blockbuttontext: {color: '#FFFFFF'},
    // block2
    blockText6: {color: '#DBDFE5'},
    blockText7: {color: '#DBDFE5'},
    blockText8: {color: '#728099'},
  //  weekly
    weeklytext1: {color: '#DBDFE5'},
    weeklytext2: {color: '#728099'},
    weekly2: {backgroundColor: '#212C40'},
 }
  
 }; 
 
 
 export default wallpaperFontConfig;
